AWSTemplateFormatVersion: 2010-09-09
Description: 'Template containing all the once-in-an-account configurations for dev accounts'

Parameters:
  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'
    
  SlackInfo:
    Type: String
    Description: <slack workspace id>:<slack channel id>. 'team_notifiche_dev_alarm' by default
    Default: TQSBH3ZS4:C02V0SRC4TV
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

Conditions:
  MilanRegion: 
    !Equals [!Ref 'AWS::Region', 'eu-south-1']

Resources:

  ###              API GATEWAY ACCOUNT-GLOBAL CONFIGURATIONS              ###
  ###########################################################################
  ### The ApiGwAccountConfig and ApiGatewayLoggingRole resources are not  ###
  ###        related to alarms; make sure to not delete them              ###
  ###########################################################################
  # - Enable API-Gateway access log capability
  ApiGwAccountConfig:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt "ApiGatewayLoggingRole.Arn"

  ###########################################################################
  ### The ApiGwAccountConfig and ApiGatewayLoggingRole resources are not  ###
  ###        related to alarms; make sure to not delete them              ###
  ###########################################################################
  # - Grant CloudWatch write access permission to AWS API-Gateway
  ApiGatewayLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"


  ###                          DEFINE ALARM TOPIC                          ###
  ############################################################################
  # - Everything written to this topic is an alarm
  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: 'dev account alarms topic: send to SQS and slack'
  
  CanPublishAlarmTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowServices
            Effect: Allow
            Principal:
              Service:
                - "events.amazonaws.com"
                - "cloudwatch.amazonaws.com"
            Action:
              - 'sns:Publish'
            Resource:
              - !Ref AlarmSNSTopic
      Topics:
        - !Ref AlarmSNSTopic
  
  # - Alarm message queue
  AlarmHistoryBufferQueue:
    Type: AWS::SQS::Queue  

  # - Alarm message queue subscription
  AlarmSNSTopicToSqsHistoryBuffer:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt AlarmHistoryBufferQueue.Arn
      Region: !Ref AWS::Region
      TopicArn: !Ref AlarmSNSTopic
  
  # - Alarm message queue policy that grant write right to SNS
  AlarmSNSTopicToSqsHistoryPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref AlarmHistoryBufferQueue
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "sns.amazonaws.com"
            Action: "sqs:SendMessage"
            Resource: !Sub ${AlarmHistoryBufferQueue.Arn}
            Condition: 
              ArnEquals: 
                aws:SourceArn: !Ref AlarmSNSTopic
      
  # - Deploy Eventbridge rules for CodePipeline/CodeBuild
  EventBridgeNotifications:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        AlarmSNSTopicName: !GetAtt  AlarmSNSTopic.TopicName
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/once4account/dev-slack/no-codestar-deploy-notifications.yaml"
      TimeoutInMinutes: 15

  # - Deploy Lambda to enrich messages
  EnrichNotificationsForSlack:
    Condition: MilanRegion
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        AlarmSNSTopicName: !GetAtt  AlarmSNSTopic.TopicName
        SlackInfo: !Ref SlackInfo
        TemplateBucketBaseUrl: !Ref TemplateBucketBaseUrl
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/once4account/dev-slack/slack-message-enrichment.yaml"
      TimeoutInMinutes: 15

  # - Connect dev alarm to email
  # - Send alarm message to email address
  # AlarmToEmail:
  #    Type: AWS::SNS::Subscription
  #    Properties: 
  #      TopicArn: !Ref AlarmSNSTopic
  #      Endpoint: !Ref AlarmEmailAddress
  #      Protocol: email


  # - Event Bridge events that generate an alarm
  # "ACM Certificate Approaching Expiration": alarm
  CertificateExpiringIsAlarmEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventRule"
      EventPattern:
        source: [ "aws.acm" ]
        detail-type: [ "ACM Certificate Approaching Expiration" ]
      Targets:
        - Arn: !Ref AlarmSNSTopic
          Id: "AlarmSnsTopic"

Outputs:

  AlarmSNSTopicArn:
    Value: !Ref AlarmSNSTopic
    Description: ARN of the Alarm SNS Topic
  
  AlarmSNSTopicName:
    Value: !GetAtt  AlarmSNSTopic.TopicName
    Description: Name of the Alarm SNS Topic
  
  Version:
    Value: !Ref Version
    Description: Give the version string as output to avoid warnings

