AWSTemplateFormatVersion: 2010-09-09
Description: Define the DNS records neede for a zone delegation

Parameters:
  EnvName:
    Type: String
    Description: The name of the installation devel, beta, uat, preprod, ...
  NameServers:
    Type: String
    Description: A pipe separated list of DNS server names

Resources:

  ZoneDelegationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: "pn.pagopa.it."
      Name: !Sub '${EnvName}.pn.pagopa.it'
      Comment: !Sub "Delegation to ${EnvName}.pn.pagopa.it zone"
      ResourceRecords:
        Fn::Split:
        - '|'
        - !Ref NameServers
      TTL: 600
      Type: NS
