#  Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
#  the License. A copy of the License is located at
#      http://aws.amazon.com/apache2.0/
#  or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and
#  limitations under the License.

AWSTemplateFormatVersion: '2010-09-09'
Description: Role to be assumed by CodePipeline service cross account
Parameters:
  S3Bucket:
    Description: S3 Bucket in Tools Account, which holds the artifacts built by codebuild
    Type: String
    Default: pre-reqs-artifactbucket-zttj4v44ig3j
  ToolsAccount:
    Description: AWS AccountNumber for Tools
    Type: Number
    Default: 911845998067
  CMKARN:
    Description: ARN of the KMS CMK creates in Tools account
    Type: String
    Default: arn:aws:kms:eu-central-1:911845998067:key/e27e5352-a612-4937-bcd8-23190baef9cc
Resources:
  CFRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ToolsAcctCodePipelineCloudFormationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                - !Ref ToolsAccount
            Action:
              - sts:AssumeRole
      Path: /
  CFPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ToolsAcctCodePipelineCloudFormationPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - cloudformation:*
              - s3:*
              - iam:PassRole
            Resource: "*"
          -
            Effect: Allow
            Action:
              - kms:*
            Resource: !Ref CMKARN
      Roles:
        -
          !Ref CFRole
  CFDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub cloudformationdeployer-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
  CFDeployerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub cloudformationdeployer-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - apigateway:POST # Create API.
              - apigateway:GET # Get API info.
              - apigateway:PATCH # Update API resources.
              - apigateway:DELETE # Delete API incase of rollback. - iam:AttachRolePolicy
              - cloudformation:*
              - cloudfront:CreateCachePolicy
              - cloudfront:CreateCloudFrontOriginAccessIdentity
              - cloudfront:CreateDistribution
              - cloudfront:CreateDistributionWithTags
              - cloudfront:CreateInvalidation
              - cloudfront:DeleteCachePolicy
              - cloudfront:DeleteCloudFrontOriginAccessIdentity
              - cloudfront:DeleteDistribution
              - cloudfront:GetCachePolicy
              - cloudfront:GetCachePolicyConfig
              - cloudfront:GetCloudFrontOriginAccessIdentity
              - cloudfront:GetCloudFrontOriginAccessIdentityConfig
              - cloudfront:GetDistribution
              - cloudfront:GetDistributionConfig  
              - cloudfront:UpdateCachePolicy
              - cloudfront:UpdateCloudFrontOriginAccessIdentity
              - cloudfront:UpdateDistribution
              - cloudfront:TagResource
              - iam:CreateRole
              - iam:CreatePolicy
              - iam:DeleteRole
              - iam:DeleteRolePolicy
              - iam:DetachRolePolicy
              - iam:GetRole
              - iam:PutRolePolicy
              - lambda:AddPermission
              - lambda:CreateFunction
              - lambda:DeleteFunction
              - lambda:InvokeFunction
              - lambda:RemovePermission
              - lambda:UpdateFunctionCode
              - lambda:GetFunctionConfiguration
              - lambda:GetFunction
              - lambda:UpdateFunctionConfiguration
              - lambda:ListTags
              - lambda:TagResource
              - lambda:UnTagResource
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:DeleteBucketPolicy
              - s3:GetAccountPublicAccessBlock
              - s3:GetBucketAcl
              - s3:GetBucketCORS
              - s3:GetBucketLocation
              - s3:GetBucketLogging
              - s3:GetBucketObjectLockConfiguration
              - s3:GetBucketOwnershipControls
              - s3:GetBucketPolicy
              - s3:GetBucketPolicyStatus
              - s3:GetBucketPublicAccessBlock
              - s3:GetBucketRequestPayment
              - s3:GetBucketTagging
              - s3:GetBucketVersioning
              - s3:GetBucketWebsite
              - s3:GetInventoryConfiguration
              - s3:GetMetricsConfiguration
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:GetObjectTagging
              - s3:GetReplicationConfiguration
              - s3:ListBucket
              - s3:ListAccessPoints
              - s3:PutBucketAcl
              - s3:PutBucketPolicy
              - s3:PutBucketTagging
              - s3:PutBucketWebsite
              - s3:PutBucketPublicAccessBlock
            Resource: "*"
          -
            Effect: Allow
            Action: 
              - ec2:AssociateRouteTable
              - ec2:AttachInternetGateway
              - ec2:DescribeAvailabilityZones
              - ec2:CreateInternetGateway
              - ec2:CreateRoute
              - ec2:CreateRouteTable
              - ec2:CreateSubnet
              - ec2:CreateTags
              - ec2:CreateVpc
              - ec2:DeleteVpc
              - ec2:DescribeVpcs
              - ec2:ModifyVpcAttribute
            Resource: "*"
          -
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:ListBucket
            Resource:
             - !Join ['',['arn:aws:s3:::',!Ref S3Bucket, '/*']]
             - !Join ['',['arn:aws:s3:::',!Ref S3Bucket]]
      Roles:
        -
          !Ref CFDeployerRole

     