AWSTemplateFormatVersion: '2010-09-09'
Description: Expose to the internet the API of a service with API-GW

Parameters:

  MicroServiceUniqueName:
    Type: String
    Description: Microservice unique name

  ApiDnsName:
    Type: String
    Description: 'The DNS name used for B2B rest API.'

  ServiceApiPath:
    Type: String
    Description: path of the exposed API

  NetworkLoadBalancerLink:
    Type: String
    Description: Link inside the VPC
  ApplicationLoadBalancerDomain:
    Type: String
    Description: Application load balancer that dispatch request to microserveces

Resources:

  PublicRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${MicroServiceUniqueName}-public-api'
      FailOnWarnings: true
      EndpointConfiguration:
        Types:
          - REGIONAL

  #PublicApiBasepathResource:
  #  Type: AWS::ApiGateway::Resource
  #  Properties:
  #    RestApiId: !Ref PublicRestApi
  #    ParentId: !GetAtt PublicRestApi.RootResourceId
  #    PathPart: !Ref ServiceApiPath

  PublicApiProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PublicRestApi
      #ParentId: !Ref PublicApiBasepathResource
      ParentId: !GetAtt PublicRestApi.RootResourceId
      PathPart: '{proxy+}'

  PublicApiProxyAnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      OperationName: !Sub 'Proxy to ${MicroServiceUniqueName} public API'
      RestApiId: !Ref PublicRestApi
      ResourceId: !Ref PublicApiProxyResource
      HttpMethod: ANY
      ApiKeyRequired: false
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.proxy: true
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Content-Type: false
        - StatusCode: 503
          ResponseParameters:
            method.response.header.Content-Type: false
      Integration:
        ConnectionType: VPC_LINK
        ConnectionId: !Ref NetworkLoadBalancerLink
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        Uri: !Sub 'http://${ApplicationLoadBalancerDomain}:8080/${ServiceApiPath}/{proxy}'
        RequestParameters:
          integration.request.path.proxy: method.request.path.proxy
          integration.request.header.Aggiunto: 'ValoreHeaderAggiunto'
        PassthroughBehavior: "WHEN_NO_MATCH"
        TimeoutInMillis: 29000
        IntegrationResponses:
          - StatusCode: 200
            SelectionPattern: ""
            ResponseParameters:
              method.response.header.Content-Type: integration.response.header.Content-Type
            ResponseTemplates:
              application/json: ""
          - StatusCode: 503
            SelectionPattern: ""
            ResponseParameters:
              method.response.header.Content-Type: integration.response.header.Content-Type
            ResponseTemplates:
              application/json: ""

  PublicRestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PublicApiProxyAnyMethod
    Properties:
      RestApiId: !Ref PublicRestApi

  PublicRestApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref PublicRestApi
      StageName: unique
      TracingEnabled: true
      DeploymentId: !Ref PublicRestApiDeployment
      AccessLogSetting:
        DestinationArn: !GetAtt "PublicApiLogGroup.Arn"
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","routeKey":"$context.routeKey","status":$context.status,"responseLatency":$context.responseLatency}'
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          MetricsEnabled: 'true'
          DataTraceEnabled: 'false'

  PublicApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1

  # Expose API to custom domain
  APIMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref ServiceApiPath
      DomainName: !Ref ApiDnsName
      RestApiId: !Ref PublicRestApi
      Stage: !Ref PublicRestApiStage

Outputs:

  # - Public API URL
  ApiGatewayUrlBeta:
    Value: !Sub 'https://${PublicRestApi}.execute-api.${AWS::Region}.amazonaws.com/unique/'
    Description: Base URL for API Requests
