---
AWSTemplateFormatVersion: 2010-09-09


Parameters:
  EnvName:
    Type: String
    Description: Nome dell'ambiente destinazione

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvName}-ecs-cluster

Outputs:
  ClusterName:
      Value: !Ref Cluster
      Export:
        Name: !Sub '${EnvName}-ecs-cluster-name'

  CluserArn:
    Description: ARN del cluster fargate
    Value: !Sub '${Cluster.Arn}'
