AWSTemplateFormatVersion: 2010-09-09
Description: ECS cluster definition for use with fargate

Parameters:
  MacroServiceName:
    Type: String
    Description: Name of the microservice logical group

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${MacroServiceName}-ecs-cluster

Outputs:
  ClusterName:
    Description: ECS cluster name
    Value: !Ref Cluster

  CluserArn:
    Description: ECS cluster ARN
    Value: !Sub '${Cluster.Arn}'
