AWSTemplateFormatVersion: '2010-09-09'
Description: Template to configure a SQS queue

Parameters:
  QueueName:
    Type: String
    Description:  Queue Name
  DelaySeconds:
    Description: 'The time in seconds that the delivery of all messages in the queue
      is delayed. You can specify an integer value of 0 to 900 (15 minutes).'
    Type: Number
    Default: '5'
  MessageRetentionPeriod:
    Description: 'The number of seconds that Amazon SQS retains a message. You can
      specify an integer value from 60 seconds (1 minute) to 1209600 seconds (14 days). '
    Type: Number
    Default: '1209600'
  DeadLetterQueueName:
    Type: String
    Description: 'Dead Letter Queue Name; use <QueueName>-DLQ if not specified.'
    Default: '-'
  MaxReceiveCount:
    Description: 'The number of times a message is delivered to the source queue before
     being moved to the dead-letter queue'
    Type: Number
    Default: '5'
  DeadLetterMessageRetentionPeriod:
    Description: 'The number of seconds that the DLQ retains a message. You can
      specify an integer value from 60 seconds (1 minute) to 1209600 seconds (14 days). '
    Type: Number
    Default: '1209600'

Conditions:
  DlqHasDefaultName: !Equals [ !Ref DeadLetterQueueName, '-' ]

Resources:

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref MaxReceiveCount
      DelaySeconds: !Ref DelaySeconds
      MessageRetentionPeriod: !Ref MessageRetentionPeriod

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::If:
          - DlqHasDefaultName
          - !Sub "${QueueName}-DLQ"
          - !Ref DeadLetterQueueName
      MessageRetentionPeriod: !Ref DeadLetterMessageRetentionPeriod

Outputs:
  # Queue info
  QueueName:
    Description: Name of source queue
    Value: !GetAtt Queue.QueueName
  QueueURL:
    Description: URL of the source queue
    Value: !Ref Queue
  QueueARN:
    Description: ARN of source queue
    Value: !GetAtt Queue.Arn

  # Dead letter queue info
  DeadLetterQueueName:
    Description: Name of source queue
    Value: !GetAtt DeadLetterQueue.QueueName
  DeadLetterQueueURL:
    Description: URL of dead-letter queue
    Value: !Ref DeadLetterQueue
  DeadLetterQueueARN:
    Description: ARN of dead-letter queue
    Value: !GetAtt DeadLetterQueue.Arn
