AWSTemplateFormatVersion: 2010-09-09
Description: 'Configure connection to AWS services on private AWS networks'

Parameters:
  VpcName:
    Type: String
    Description: 'VPC name: pn-dev, pn-uat, extreg-dev, ...'
  VpcNumber:
    Type: String
    Description: Second byte from the left for VPC CIDR

  VpcId:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  RouteTableIds:
    Type: List<String>


Resources:

  ###                  PRIVATE CONNECTIONS CONFIGURATIONS                  ###
  ############################################################################

  ### to S3 service ###
  S3VPCGatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Gateway
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: '*'
            Effect: Allow
            Resource: '*'
            Principal: '*'
      RouteTableIds: !Ref RouteTableIds
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref VpcId

  ### to CASSANDRA service ###
  CassandraInterfaceEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref InterfaceSecurityGroup
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.cassandra'
      SubnetIds: !Ref Subnets
      VpcId: !Ref VpcId

  ### to SQS service ###
  SQSInterfaceEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref InterfaceSecurityGroup
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.sqs'
      SubnetIds: !Ref Subnets
      VpcId: !Ref VpcId


  ###         ALLOW ACCESS TO SERVICES ELASTIC NETWORK INTERFACES         ###
  ###########################################################################
  InterfaceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Controls Inbound Access to the VPC Interface Endpoint from within the VPC'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - FromPort: '0'
          ToPort: '65535'
          IpProtocol: tcp
          CidrIp: !Join ['', ["10.", !Ref "VpcNumber", ".0.0/16" ]]
      Tags:
        - Key: Name
          Value: !Sub '${VpcName}-Interface-Endpoint-SecGrp'

