AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvName:
    Type: String
    Description: Nome dell'ambiente destinazione
  EnvNumber:
    Type: String
    Description: Second byte from the left for VPC CIDR
  

Resources:

  # Microservices VPC:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Join ['', ["10.", !Ref "EnvNumber", ".0.0/16" ]]
      EnableDnsSupport: true
      EnableDnsHostnames: false
      Tags:
      - Key: Name
        Value: !Sub ${EnvName}-VPC

  # Internet connections
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvName}-VPC
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # Public subnets commons
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvName} Public Routes
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Public subnet 1
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Join ['', ["10.", !Ref "EnvNumber", ".1.0/24" ]]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvName} Public Subnet (AZ1)
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  # Public subnet 2
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Join [ '', [ "10.", !Ref "EnvNumber", ".2.0/24" ] ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvName} Public Subnet (AZ2)
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  # Network security groups
  WebappSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvName}-webapp-security-group
      GroupDescription: "ingres tcp 8080, egress all"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: "0.0.0.0/0"
      VpcId: !Ref VPC
  # Application load balancer
  PrivateApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internal
      IpAddressType: ipv4
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref WebappSecurityGroup

  # Network load balancer
  PrivateNetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: network
      Scheme: internal
      IpAddressType: ipv4
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

  # API Gateway integrations
  PrivateNlbLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: !Sub '${EnvName}-priv-nlb-link'
      Description: "API-GW link to Network load balancer"
      TargetArns:
        - !Ref PrivateNetworkLoadBalancer
  #PrivateAlbLink:
  #  Type: AWS::ApiGatewayV2::VpcLink
  #  Properties:
  #    Name: !Sub '${EnvName}-priv-alb-link'
  #    SecurityGroupIds:
  #      - !Ref WebappSecurityGroup
  #    SubnetIds:
  #      - !Ref PublicSubnet1
  #      - !Ref PublicSubnet2

  # Inter microservice comunication queue
  DeliveryPushInputsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${EnvName}-delivery_push_inputs'
      DelaySeconds: 2
      MessageRetentionPeriod: 36000 # 10h
      ReceiveMessageWaitTimeSeconds: 5
      VisibilityTimeout: 10 # seconds
  ExternalChannelsInputsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${EnvName}-external_channel_inputs'
      DelaySeconds: 2
      MessageRetentionPeriod: 36000 # 10h
      ReceiveMessageWaitTimeSeconds: 5
      VisibilityTimeout: 10 # seconds
  ExternalChannelsOutputsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${EnvName}-external_channel_outputs'
      DelaySeconds: 2
      MessageRetentionPeriod: 36000 # 10h
      ReceiveMessageWaitTimeSeconds: 5
      VisibilityTimeout: 10 # seconds


Outputs:
  # - API Gateway access informations
  PrivateNetworkLoadBalancer:
    Value: !Ref PrivateNetworkLoadBalancer
    Description: Identificativo VPC Network Load Balancer
    Export:
      Name: !Sub '${EnvName}-nlb-id'
  PrivateApplicationLoadBalancer:
    Value: !Ref PrivateApplicationLoadBalancer
    Description: Identificativo VPC Application Load Balancer
    Export:
      Name: !Sub '${EnvName}-alb-id'
  PrivateNlbLink:
    Value: !Ref PrivateNlbLink
    Description: Used by API-Gw to connect into VPC
    Export:
      Name: !Sub '${EnvName}-nlb-link-id'
  PrivateApplicationLoadBalancerDomain:
    Value: !Sub '${PrivateApplicationLoadBalancer.DNSName}'
    Description: Identificativo VPC Application Load Balancer
    Export:
      Name: !Sub '${EnvName}-alb-domain'
  VpcId:
    Value: !Ref VPC
    Description: Id della VPC
    Export:
      Name: !Sub '${EnvName}-vpc-id'
  PublicSubnet1Id:
    Value: !Ref PublicSubnet1
    Description: Id subnet 1
    Export:
      Name: !Sub '${EnvName}-subnet1'
  PublicSubnet2Id:
    Value: !Ref PublicSubnet2
    Description: Id subnet 2
    Export:
      Name: !Sub '${EnvName}-subnet2'
  DeliveryPushInputsQueueArn:
    Value: !Sub '${DeliveryPushInputsQueue.Arn}'
    Description: 'workflow input events queue ARN'
    Export:
      Name: !Sub '${EnvName}-delpush-input-queue-arn'
  ExternalChannelsInputsQueueArn:
    Value: !Sub '${ExternalChannelsInputsQueue.Arn}'
    Description: 'external channel input events queue ARN'
    Export:
      Name: !Sub '${EnvName}-extchannel-input-queue-arn'
  ExternalChannelsOutputsQueueArn:
    Value: !Sub '${ExternalChannelsOutputsQueue.Arn}'
    Description: 'external channel output events queue ARN'
    Export:
      Name: !Sub '${EnvName}-extchannel-output-queue-arn'
