AWSTemplateFormatVersion: "2010-09-09"
Description: "Backup Plan template for AWS Backups"
Parameters:

  LifecycleDeleteAfterDays:
    Type: Number
    Default: 35
    Description: Specifies the number of days after creation that a recovery point is deleted. Must be greater than 90 days plus MoveToColdStorageAfterDays.

  BackupCronExpression:
    Type: String

  CompletionWindowMinutes:
    Type: Number
    Default: 600

  StartWindowMinutes:
    Type: Number
    Default: 60

Resources:
  BackupVault:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: !Sub 'BackupVault_Dynamodb_${AWS::StackName}'

  BackupVaultS3:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: !Sub 'BackupVault_S3_${AWS::AccountId}'

  AwsS3BatchOperationBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub pn-s3-batch-operation-${AWS::Region}-${AWS::AccountId}

  BackupPlan:
    Type: "AWS::Backup::BackupPlan"
    Properties:
      BackupPlan:
        BackupPlanName: !Sub 'BackupPlan_${AWS::StackName}'
        BackupPlanRule:

          - RuleName: "RuleForDailyBackups"
            TargetBackupVault: !Ref BackupVault
            ScheduleExpression: !Ref BackupCronExpression
            StartWindowMinutes: !Ref StartWindowMinutes
            CompletionWindowMinutes : !Ref CompletionWindowMinutes
            EnableContinuousBackup: true
            Lifecycle:
              DeleteAfterDays:
                Ref: LifecycleDeleteAfterDays

  BackupRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "backup.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"

  BackupRoleS3:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub pn-backup-s3-role-${AWS::AccountId}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "backup.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSBackupServiceRolePolicyForS3Backup"
        - "arn:aws:iam::aws:policy/AWSBackupServiceRolePolicyForS3Restore"

  S3batchOperation:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub pn-S3BatchOperation-role-${AWS::AccountId}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "batchoperations.s3.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: pn-S3BatchOperationPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:RestoreObject
                Resource: "arn:aws:s3:::*"
              - Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${AwsS3BatchOperationBucket}/*"

  TagBasedBackupSelection:
    Type: "AWS::Backup::BackupSelection"
    Properties:
      BackupSelection:
        SelectionName: "TagBasedBackupSelection"
        IamRoleArn: !GetAtt BackupRole.Arn
        Resources:
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-ConfidentialObjects
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-EcRichieste
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-EcRichiesteMetadati
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-SsAnagraficaClient
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-EcAnagrafica
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/PnSsTableDocumentiStreamMetadati
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-AuditStorage
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-SsDocumenti
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-SmStates
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-SsTipologieDocumenti
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-addressManager-AnagraficaClient
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-addressManager-Cap
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-addressManager-Country
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-addressManager-NormalizzatoreBatch
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-addressManager-PNRequest
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-addressManager-ShedLock
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-legal-conservation-request
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-legal-conservation-request-history
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-SsScadenzaDocumenti
      BackupPlanId: !Ref BackupPlan
