AWSTemplateFormatVersion: 2010-09-09
Description: Template for reducing costs on PN with ec2 and ecs

Parameters:  
  StopEc2FunctionTagName:
    Type: String
    Default: 'tostop'
    Description: Name of EC2 Tag that will be stopped

  StopEc2FunctionTagValue:
    Type: String
    Default: 'true'
    Description: Value of EC2 Tag that will be stopped

  StopEc2FunctionTagNameCronExpression:
    Type: String
    Default: 'cron(0 19 * * ? *)'
    Description: Cron expression when ec2 stop

  StopEcsFunctionCronExpression:
    Type: String
    Default: 'cron(0 19 ? * MON-FRI *)'
    Description: Cron expression when ecs stop

  StartEcsFunctionCronExpression:
    Type: String
    Default: 'cron(0 4 ? * MON-FRI *)'
    Description: Cron expression when ecs start

  ECSClusterName:
    Type: String
    Default: ''
    Description: Cluster Ecs Name

  PdfRasterECSClusterName:
    Type: String
    Default: ''
    Description: 'Cluster Ecs Name'

  EnvironmentType:
    Type: String
    Default: ''
    Description: Environment type

  LambdasBucketName:
    Type: String
    Description: Bucket for save Json with desire count of Ecs

  LambdasBasePath:
    Type: String
    Description: S3 object key prefix for the lambda artifacts
    Default: ''

  PnCoreAwsAccountId:
    Type: String
    Description: Core Account ID (leave blank in Core account)
    Default: ''

Conditions:
  IsNotProdAccount: !Not [ !Equals [!Ref EnvironmentType, prod ] ]
  IsNotUatAccount: !Not [ !Equals [!Ref EnvironmentType, uat ] ]
  IsConfinfoAccount: !Not [ !Equals [!Ref PnCoreAwsAccountId, '' ] ]
  IsStopEcsService: !And [ !Condition IsNotProdAccount, !Condition IsNotUatAccount ]
  IsStopEcsServiceConfinfo: !And [ !Condition IsNotProdAccount, !Condition IsNotUatAccount, !Condition IsConfinfoAccount]
  IsHotfixAccount: !Equals [!Ref EnvironmentType, hotfix ]

#LAMBDA STOP EC2

Resources:
  StopEc2Function:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.14
      Handler: ec2_saving.lambda_handler
      FunctionName: !Sub 'Lambda-Ec2-stop-${EnvironmentType}'
      Code:
        S3Bucket: !Ref LambdasBucketName
        S3Key: !Sub "${LambdasBasePath}/pn-cost-saving.zip"
      Environment:
        Variables:
          StopEc2FunctionTagName:
            Ref: StopEc2FunctionTagName
          StopEc2FunctionTagValue:
            Ref: StopEc2FunctionTagValue
      Role:
        Fn::GetAtt:
          - StopEc2FunctionRole
          - Arn

  StopEc2FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StopEc2FunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:StopInstances
                Resource: "*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: arn:aws:logs:*:*:*

  StopEc2FunctionSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: !Ref StopEc2FunctionTagNameCronExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt StopEc2Function.Arn
          Id: StopEc2Function

  StopEc2FunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref StopEc2Function
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StopEc2FunctionSchedule.Arn
      SourceAccount: !Ref AWS::AccountId

  StopEc2FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy : Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StopEc2Function}"
      RetentionInDays: 3

#LAMBDA ECS COST SAVING

  EcsCostSavingFunction:
    Condition: IsStopEcsService
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.14
      Timeout: 120
      Handler: ecs_saving.lambda_handler
      FunctionName: !Sub 'Lambda-Ecs-CostSaving-${EnvironmentType}'
      Code:
        S3Bucket: !Ref LambdasBucketName
        S3Key: !Sub "${LambdasBasePath}/pn-cost-saving.zip"
      Environment:
        Variables:
          EcsDesireCountBucket:
            Ref: LambdasBucketName
          EnvironmentType:
            Ref: EnvironmentType
          AwsAccountId: 
            Fn::Sub: "${AWS::AccountId}"
          ECSClusterName: 
            Fn::If:
              - IsStopEcsServiceConfinfo
              - !Join 
                  - ","
                  - 
                    - Ref: ECSClusterName
                    - Ref: PdfRasterECSClusterName
              - Ref: ECSClusterName
      Role:
        Fn::GetAtt:
          - EcsOptimizedCostFunctionRole
          - Arn

  EcsOptimizedCostFunctionRole:
    Condition: IsStopEcsService
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EcsOptimizedCostFunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${LambdasBucketName}"
                  - !Sub "arn:aws:s3:::${LambdasBucketName}/*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:github-token-*"
              - Effect: Allow
                Action:
                  - ecs:*
                Resource:
                  Fn::If:
                    - IsStopEcsServiceConfinfo
                    - 
                      - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*/${ECSClusterName}"
                      - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*/${ECSClusterName}/*"
                      - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*/${PdfRasterECSClusterName}"
                      - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*/${PdfRasterECSClusterName}/*"
                    - 
                      - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*/${ECSClusterName}"
                      - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*/${ECSClusterName}/*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: arn:aws:logs:*:*:*

  StopEcsFunctionSchedule:
    Condition: IsStopEcsService
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression:
        Fn::If:
        - IsHotfixAccount
        - cron(0 19 ? * * *)
        - !Ref StopEcsFunctionCronExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt EcsCostSavingFunction.Arn
          Id: StopEcsFunction
          Input: '{"action": "stop"}'

  StopEcsFunctionInvokePermission:
    Condition: IsStopEcsService
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref EcsCostSavingFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StopEcsFunctionSchedule.Arn
      SourceAccount: !Ref AWS::AccountId

  StopEcsFunctionLogGroup:
    Condition: IsStopEcsService
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy : Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${EcsCostSavingFunction}"
      RetentionInDays: 3

  StartEcsFunctionSchedule:
    Condition: IsStopEcsService
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression:
        Fn::If:
        - IsHotfixAccount
        - cron(0 18 1 * ? *)
        - !Ref StartEcsFunctionCronExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt EcsCostSavingFunction.Arn
          Id: StartEcsFunction
          Input: '{"action": "start"}'

  StartEcsFunctionInvokePermission:
    Condition: IsStopEcsService
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref EcsCostSavingFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StartEcsFunctionSchedule.Arn
      SourceAccount: !Ref AWS::AccountId

  StartEcsFunctionLogGroup:
    Condition: IsStopEcsService
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy : Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${EcsCostSavingFunction}-Start"
      RetentionInDays: 3
