AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of elasticache cluster

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project

  AlarmSNSTopicName:
    Type: String
    Description: "A name of an SNS topic where to send alarm." 

  NodeType:
    Type: String
    Description: Cache node type (i.e. cache.t2.micro)

  Replicas:
    Type: Number
    Description: Number of nodes

  VpcSubnets:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: Private subnets to deploy resources into

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: VPC id for the cluster

  CPUUtilizationThreshold:
    Type: Number
    Description: The threshold percentage of CPU usage.
    MinValue: 0
    MaxValue: 100
    Default: 60

  EngineCPUUtilizationThreshold:
    Type: Number
    Description: The threshold percentage of CPU utilization of the Redis engine thread
    MinValue: 0
    MaxValue: 100
    Default: 60

  RedisMemoryUsedThreshold:
    Type: Number
    Description: The threshold percentage for the amount of memory utilized.
    MinValue: 0
    MaxValue: 100
    Default: 60

  CurrentConnectionsThreshold:
    Type: Number
    Description: "The threshold number of concurrent and active connections. (Max connections: 65000)."
    MinValue: 0
    MaxValue: 65000
    Default: 60000

  AccessStringDefaultUser:
    Type: String
    Description: "AccessString for elasticache redis default user"
    Default: "on ~* +@all"

  UserIdDefaultUser:
    Type: String
    Description: "UserId for elasticache redis default user"
    Default: "default-redis"

  UsernameDefaultUser:
    Type: String
    Description: "Username for elasticache redis default user"
    Default: "default"

  AccessStringUser1:
    Type: String
    Description: "AccessString for elasticache redis user"
    Default: "on ~b2bauth::* +@all"

  UserIdUser1:
    Type: String
    Description: "UserId for elasticache redis user"
    Default: "iam-user-b2b-auth"

  UsernameUser1:
    Type: String
    Description: "Username for elasticache redis user"
    Default: "iam-user-b2b-auth"

  UserIdLogExtractor:
    Type: String
    Description: "UserId for elasticache redis user"
    Default: "iam-user-logextractor"

  UsernameLogExtractor:
    Type: String
    Description: "Username for elasticache redis user"
    Default: "iam-user-logextractor"

Resources:

  RedisServerless:
    Type: AWS::ElastiCache::ServerlessCache
    Properties:
      ServerlessCacheName: !Sub ${ProjectName}-redis-serverless
      Engine: redis
      Description: Redis Serverless Cache for Logextractor
      MajorEngineVersion: 7
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      SubnetIds: !Ref VpcSubnets
      KmsKeyId: !Ref RedisServerlessEncryptionKey
      UserGroupId: !Ref ElastiCacheUserGroup

  RedisServerlessEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Redis Serverless Cache Encryption Key
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              Service: elasticache.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'

  SubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      Description: Cache Subnet Group
      SubnetIds: !Ref VpcSubnets

  AllowedSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Earn permissions to access cache
      GroupName: !Sub ${ProjectName}-cache
      VpcId: !Ref VpcId

  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Open Redis port
      GroupName: !Sub ${ProjectName}-redis
      SecurityGroupIngress:
        - FromPort: 6379
          IpProtocol: tcp
          SourceSecurityGroupId: !GetAtt AllowedSecurityGroup.GroupId
          ToPort: 6380
      VpcId: !Ref VpcId

  RedisReplicationGroup:
    Type: "AWS::ElastiCache::ReplicationGroup"
    Properties:
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: false
      CacheNodeType: !Ref NodeType
      AutoMinorVersionUpgrade: true
      AutomaticFailoverEnabled: false
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: redis
      ReplicationGroupDescription:
        Fn::Sub: ${ProjectName}-redis-replication-group
      ReplicasPerNodeGroup: !Ref Replicas
      SecurityGroupIds:
         - "Fn::GetAtt":
            - SecurityGroup
            - GroupId

  ElastiCacheUserGroup:
    Type: AWS::ElastiCache::UserGroup
    Properties:
      Engine: redis
      UserGroupId: !Sub ${ProjectName}-redis-user-group
      UserIds: 
        - !Ref DefaultElasticCacheUser
        - !Ref ElasticCacheUser1

  DefaultElasticCacheUser:
    Type: AWS::ElastiCache::User
    Properties:
      AccessString: !Ref AccessStringDefaultUser
      AuthenticationMode: 
        Type: no-password-required
      Engine: redis
      UserId: !Ref UserIdDefaultUser
      UserName: !Ref UsernameDefaultUser

  ElasticCacheUser1:
    Type: AWS::ElastiCache::User
    Properties:
      AccessString: !Ref AccessStringUser1
      AuthenticationMode: 
        Type: iam
      Engine: redis
      UserId: !Ref UserIdUser1
      UserName: !Ref UsernameUser1

  ElasticCacheLogExtractorUser:
    Type: AWS::ElastiCache::User
    Properties:
      AccessString: !Ref AccessStringDefaultUser
      AuthenticationMode: 
        Type: iam
      Engine: redis
      UserId: !Ref UserIdLogExtractor
      UserName: !Ref UsernameLogExtractor

Outputs:
  ElasticacheSecurityGroup:
    Description: The id of the security group that can access the cache cluster
    Value: !GetAtt AllowedSecurityGroup.GroupId

  RedisEndpoint:
    Description: The endpoint Address for Redis serverless
    Value:
        - Fn::GetAtt:
          - RedisServerless
          - Endpoint.Address

  RedisServerlessArn:
    Description: The Redis serverless Arn
    Value: !GetAtt RedisServerless.ARN

  RedisServerlessName:
    Description: The Redis serverless name
    Value: !Ref RedisServerless

  ElasticacheUserArn1:
    Description: ElasticCacheUser1 Arn
    Value: !GetAtt ElasticCacheUser1.Arn

  ElasticacheUserId1:
    Description: Id of the User1
    Value: !Ref UserIdUser1

  ElasticCacheLogExtractorUserArn:
    Description: ElasticCacheLogExtractorUser Arn
    Value: !GetAtt ElasticCacheLogExtractorUser.Arn

  ElasticCacheLogExtractorUserId:
    Description: Id of the LogExtractorUser
    Value: !Ref UsernameLogExtractor