AWSTemplateFormatVersion: "2010-09-09"
Description: "API Gateway used by CN"

Transform:
  - UpdateDeploymentTransform

Parameters:
  ProjectName:
    Type: String

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  CNApiDnsName:
    Type: String
    Description: 'DNS custom domain for CN API'

  ConfidentialInfoAccountId:
    Type: String

  #SNS Topic Alarm Arn and Name
  AlarmSNSTopicArn:
    Type: String
    Description: "An ARN of an SNS topic where to send alarm when log line includes ERROR or FATAL" 

  CNLatencyLimit:
    Type: Number
    Default: '2000'

  EnvironmentType:
    Type: String

  CNBackendCidrs:
    Type: String
    Default: ''

  BucketName:
    Type: String

  BucketBasePath:
    Type: String


  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'

Conditions:
  IsDev: !Equals [ !Ref EnvironmentType, 'dev' ]
  IsTest: !Equals [ !Ref EnvironmentType, 'test' ]
  IsProd: !Equals [ !Ref EnvironmentType, 'prod' ]
  IsCNEnabled: !Or [ !Condition IsDev, !Condition IsTest, !Condition IsProd ]

Resources:

  # Expose PN-Delivery microservice public API with API-GW for B2B usage
  CNPublicAPI:
    Type: AWS::CloudFormation::Stack
    Condition: IsCNEnabled
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service-openapi.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-cn'
        IntendedUsage: CN_BE
        DnsName: !Ref CNApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'cn'
        NetworkLoadBalancerLink: '-'
        ApplicationLoadBalancerDomain: '-'
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn
        ConfidentialInfoAccountId: !Ref ConfidentialInfoAccountId
        OpenApiBucketName: !Ref BucketName
        OpenApiBucketKey: !Sub ${BucketBasePath}/docs/openapi/aws/api-cn-CN_BE-aws.yaml
        OpenApiMode: 'INCLUDE'

  CNPublicApiWaf:
    Type: AWS::CloudFormation::Stack
    Condition: IsCNEnabled
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-cn'
        IntendedUsage: CN_BE
        APIGatewayARNs: !GetAtt CNPublicAPI.Outputs.APIGatewayARN
        Limit: 0 # disable IP limit based rule
        AllowedCidrs: !Ref CNBackendCidrs

  CNUsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    Condition: IsCNEnabled
    Properties:
      UsagePlanName: CN_BE
      ApiStages:
        - ApiId: !GetAtt CNPublicAPI.Outputs.RestApiId
          Stage: unique # it is hardocded in api-gw-expose-service-openapi.yaml stack as well
      Description: Usage Plan for CN
      Quota:
        Limit: 1000000
        Period: DAY
      Throttle:
        BurstLimit: 200
        RateLimit: 100