AWSTemplateFormatVersion: 2010-09-09
Description: 'This template deploys the queues needed for communication between microservices and 
              API gateway custom domains'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  AlarmSNSTopicArn:
    Type: String
    Description: 'ARN of alarm SNS Topic'

  MetricNamespace:
    Type: String
    Description: 'ARN of alarm SNS Topic'
    Default: 'AdvancedMetric'

  Version:
    Type: String
    Description: 'Version'

Resources:

  EMDDownstreamDetectionAlarm:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/custom-metric.yaml"
      Parameters:
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        MetricName: !Sub "${ProjectName}-EMD_DownstreamDetection
        MetricNamespace: !!Ref MetricNamespace
        LogGroupName: /aws/ecs/pn-emd-integration
        FilterPattern: '{ $.level = \"ERROR\" && $.logger_name = \"*ClientImpl\" && $.message = \"[DOWNSTREAM]*\" && $.message = \"*returned errors=*\"}'
        Period: 300
        Threshold: 1
        EvaluationPeriods: 12
        DatapointsToAlarm: 1
        Statistic: Sum
        ComparisonOperator: GreaterThanOrEqualToThreshold
        HasOncall: false

Outputs:
  Version:
    Value: !Ref Version
    Description: 'keep track of used projects commitIds'