AWSTemplateFormatVersion: 2010-09-09
Description: 'This template deploys the base infra for PN. VPC, AWS services endpoints, 
              load balancer, ECS cluster'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  VpcId:
    Type: String
    Description: VpcId of the VPC where to install PN-CORE
  VpcCidr:
    Type: String
    Description: Cidr of the VPC where to install PN-CORE
  VpcSubnets:
    Type: String
    Description: subnets where to install PN-CORE
  VpcSubnetsRoutingTables:
    Type: String
    Description: routing table for subnets where to install PN-CORE
  PrivateHostedZone:
    Type: String
    Description: private hosted zone where register the application load balancer

  RaddApiCertificateArn:
    Type: String
    Description: Radd Api certificate ARN

  RaddApiDnsName:
    Type: String
    Description: Radd Api DNS Name

  HostedZoneId:
    Type: String
    Description: hosted zone where register the network load balancer

  InternalNlbIps:
    Description: The list of ips of the internal network load balancer
    Type: String

  BucketSuffix:
    Type: String
    Default: "001"
    Description: Suffix to the log bucket name
  DataLakeAccountId1:
    Type: String
    Default: '-'
    Description: Data lake can read logs
  DataLakeAccountId2:
    Type: String
    Default: '-'
    Description: Data lake can read logs

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'
    
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  VpcEndpointsRequired:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
      
  ApplicationLoadBalancerArn: 
    Type: String
    Default: '-'
    Description: Application load balancer

  ApplicationLoadBalancerAwsDns: 
    Type: String
    Default: '-'
    Description: Application load balancer AWS DNS

  ApplicationLoadBalancerAwsDnsZoneId:
    Type: String
    Default: '-'
    Description: Application load balancer AWS DNS Zone ID

  ApplicationLoadBalancerListenerArn:
    Type: String
    Default: '-'
    Description: Application load balancer listener ARN

  NetworkLoadBalancerLink: 
    Type: String
    Default: '-'
    Description: Network load balancer VpcLink (used by api-gw)

  WebappSecurityGroupId: 
    Type: String
    Default: '-'
    Description: ALB security group ID

  VpcEgressSubnetsIds:
    Type: String
    Default: '-'
    Description: List of egress subnets

  LogRetention:
    Type: Number
    Default: 14

  # pass-through parameters
  AlarmSNSTopicArn:
    Type: String
  AlarmSNSTopicName:
    Type: String
  EcsDefaultSecurityGroup:
    Type: String
  LogsBucketKmsKeyArn:
    Type: String
  LogsBucketName:
    Type: String
  SafeStorageAccountId:
    Type: String
  CdcKinesisStreamName:
    Type: String
  CdcKinesisStreamArn:
    Type: String
  CdcKinesisStreamKeyArn:
    Type: String
  LogsKinesisStreamName:
    Type: String
  LogsKinesisStreamArn:
    Type: String
  LogsKinesisStreamKeyArn:
    Type: String
  ApiKeyTablesEncryptKeyId:
    Type: String
  SafestorageLoggerLogGroupName:
    Type: String
  RedisServerlessArn:
    Type: String
  RedisServerlessName:
    Type: String
  ElasticCacheUser1Arn:
    Type: String

  LogsKinesisMaxAgeInMilliseconds:
    Type: Number
    Default: 36000000 # 10 hours
    Description: 'MaxAgeInMilliseconds for Kinesis Logs GetRecords'

  LogsKinesisMaxAgeInMillisecondsOncall:
    Type: Number
    Default: 216000000 # 60 hours
    Description: 'MaxAgeInMilliseconds for Kinesis Logs GetRecords'

  CdcKinesisMaxAgeInMilliseconds:
    Type: Number
    Default: 3600000 # 1 hour
    Description: 'MaxAgeInMilliseconds for Kinesis Cdc GetRecords'

  CdcKinesisMaxAgeInMillisecondsOncall:
    Type: Number
    Default: 43200000 # 12 hours
    Description: 'MaxAgeInMilliseconds for Kinesis Cdc GetRecords'


  # Data Monitoring pass-through params
  DynamoDbExportTableNames:
    Type: String
    Description: 'Comma separated list of DynamoDB tables to export'
    Default: ''

  DynamoDbExportPrefix:
    Type: String
    Description: 'Prefix for the DynamoDB export'
    Default: 'incremental2024'

  ConfinfoDynamoDbExportBucketName:
    Type: String
    Description: 'Bucket name for the DynamoDB export for Confinfo Account'

  ParquetBucketPath:
    Type: String
    Description: parquet files s3 bucket path
    Default: 'parquet'

  DataMonitoringCodebuildComputeType:
    Type: String
    Description: Codebuild compute type (https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html)
    Default: BUILD_GENERAL1_LARGE

  DataMonitoringIndexCronExpression:
    Type: String
    Description: Cron expression for the scheduled rule, e.g. cron(0 9 * * ? *)
    Default: '' # example: 'cron(0 9 * * ? *)'

  DataMonitoringScriptVersion:
    Type: String
    Description: 'The version of the BI or not BI EC metadata'
    Default: ec_metadata_extract_v0_1

  DataMonitoringPrototypeVersion:
    Type: String
    Description: Version of the pn-prototype scripts
    Default: main

Conditions:
  IsAlbArnEmpty: !Equals [ !Ref ApplicationLoadBalancerArn, '-' ]
  IsAlbArnDnsEmpty: !Equals [ !Ref ApplicationLoadBalancerAwsDns, '-' ]
  IsAlbArnDnsZoneIdEmpty: !Equals [ !Ref ApplicationLoadBalancerAwsDnsZoneId, '-' ]
  IsAlbListenerArnEmpty: !Equals [ !Ref ApplicationLoadBalancerListenerArn, '-' ]
  IsNetworkLoadBalancerLinkEmpty: !Equals [ !Ref NetworkLoadBalancerLink, '-' ]
  IsWebappSecurityGroupIdEmpty: !Equals [ !Ref WebappSecurityGroupId, '-' ]
  RequiresAlbCreation: !Or [ !Condition IsAlbArnEmpty, !Condition IsAlbArnDnsEmpty, !Condition IsAlbArnDnsZoneIdEmpty, !Condition IsAlbListenerArnEmpty, !Condition IsNetworkLoadBalancerLinkEmpty, !Condition IsWebappSecurityGroupIdEmpty ]
  
  RequiresVpcEndpoints: !Equals [ !Ref VpcEndpointsRequired, true ]

  IsEgressDefined: !Not [ !Equals [ !Ref VpcEgressSubnetsIds, '-' ] ]
Resources:

  ###                       VPC BASE CONFIGURATIONS                       ###
  ###########################################################################

  # VPC and subnets
  #VPC:
  #  Type: AWS::CloudFormation::Stack
  #  Properties:
  #    TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/vpc.yaml"
  #    Parameters:
  #      VpcName: !Ref ProjectName
  #      VpcNumber: !Ref VpcNumber

  # Private connection from subnets to AWS services
  VPCEndpoints:
    Type: AWS::CloudFormation::Stack
    Condition: RequiresVpcEndpoints
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/vpc-endpoints.yaml"
      Parameters:
        VpcName: !Ref ProjectName
        VpcCidr: !Ref VpcCidr
        Subnets: !Ref VpcSubnets
        RouteTableIds: !Ref VpcSubnetsRoutingTables
        VpcId: !Ref VpcId

  # LoadBalancer
  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Condition: RequiresAlbCreation
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/load-balancer.yaml"
      Parameters:
        LoadBalancerName: !Ref ProjectName
        Subnets: !Ref VpcSubnets
        VpcId: !Ref VpcId
        RaddApiCertificateArn: !Ref RaddApiCertificateArn
        RaddApiDnsName: !Ref RaddApiDnsName
        HostedZoneId: !Ref HostedZoneId
        InternalNlbIps: !Ref InternalNlbIps

  # Load balancer private fixed DNS
  Route53RecordSetGroup:
    Condition: RequiresAlbCreation
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub 'alb.core.${ProjectName}.internal'
      Type: A
      HostedZoneId: !Ref PrivateHostedZone  
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.Outputs.ApplicationLoadBalancerDomain 
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt LoadBalancer.Outputs.ApplicationLoadBalancerDomainZone

  ###                             ECS CLUSTER                             ###
  ###########################################################################

  # The cluster
  ECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-cluster.yaml"
      Parameters:
        MacroServiceName: !Sub '${ProjectName}-core'
  
  # Exporter role
  LogsExporterRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-bucket-access-role.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        LogsBucketName: !Ref LogsBucketName
        LogsBucketKmsKeyArn: !Ref LogsBucketKmsKeyArn
        DataLakeAccountId1: !Ref DataLakeAccountId1
        DataLakeAccountId2: !Ref DataLakeAccountId2
        SafeStorageAccountId: !Ref SafeStorageAccountId
        BucketSuffix: !Ref BucketSuffix 

  ###                       CLOUDFORMATION TRANSFORM LAMBDAS              ###
  ###########################################################################

  UpdateDeploymentTransform:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/lambda-update-deployment-transform.yaml"

  CloudWatchDashboardTransform:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/lambda-cloudwatch-dashboard-transform.yaml"

Outputs:

  # VPC outputs
  VpcId:
    Value: !Ref VpcId
    Description: infrastructure VPC id

  SubnetsIds:
    Value: !Ref VpcSubnets
    Description: Subnets

  # Load balancers outputs
  NetworkLoadBalancerLink:
    Value: !If [ RequiresAlbCreation, !GetAtt LoadBalancer.Outputs.NetworkLoadBalancerLink, !Ref NetworkLoadBalancerLink ]
    Description: Used by API-Gw to connect into VPC

  ApplicationLoadBalancerListenerArn:
    Value: !If [ RequiresAlbCreation, !GetAtt LoadBalancer.Outputs.ApplicationLoadBalancerListenerArn, !Ref ApplicationLoadBalancerListenerArn ]
    Description: Application Load Balancerlistener Arn

  ApplicationLoadBalancerDomain:
    Value: !If [ RequiresAlbCreation, !GetAtt LoadBalancer.Outputs.ApplicationLoadBalancerDomain, !Ref ApplicationLoadBalancerAwsDns ]
    Description: Application Load Balancer Domain to use for http URL

  AlbSecurityGroup:
    Value: !If [ RequiresAlbCreation, !GetAtt LoadBalancer.Outputs.AlbSecurityGroup, !Ref WebappSecurityGroupId ]

  # ECS Cluster
  ECSClusterName:
    Value: !GetAtt ECSCluster.Outputs.ClusterName
    Description: ECS cluster name

  # Log exports outputs
  LogsExporterRoleArn:
    Description: Role used to export logs to external bucket
    Value: !GetAtt LogsExporterRole.Outputs.LogsIngestionRoleArn
  LogsExporterPolicyArn:
    Description: Policy used by LogsExporterRoleArn Role
    Value: !GetAtt LogsExporterRole.Outputs.LogsIngestionPolicyArn
    
  LogRetention:
    Value: !Ref LogRetention
    
  # pass-though parameters
  AlarmSNSTopicArn:
    Value: !Ref AlarmSNSTopicArn
  AlarmSNSTopicName:
    Value: !Ref AlarmSNSTopicName
  EcsDefaultSecurityGroup:
    Value: !Ref EcsDefaultSecurityGroup
  SafeStorageAccountId:
    Value: !Ref SafeStorageAccountId
  LogsBucketKmsKeyArn:
    Value: !Ref LogsBucketKmsKeyArn
  LogsBucketName:
    Value: !Ref LogsBucketName
  CdcKinesisStreamName:
    Value: !Ref CdcKinesisStreamName
  CdcKinesisMaxAgeInMilliseconds:
    Value: !Ref CdcKinesisMaxAgeInMilliseconds    
  CdcKinesisMaxAgeInMillisecondsOncall:
    Value: !Ref CdcKinesisMaxAgeInMillisecondsOncall    
  CdcKinesisStreamArn:
    Value: !Ref CdcKinesisStreamArn
  CdcKinesisStreamKeyArn:
    Value: !Ref CdcKinesisStreamKeyArn
  LogsKinesisStreamName:
    Value: !Ref LogsKinesisStreamName
  LogsKinesisMaxAgeInMilliseconds:
    Value: !Ref LogsKinesisMaxAgeInMilliseconds
  LogsKinesisMaxAgeInMillisecondsOncall:
    Value: !Ref LogsKinesisMaxAgeInMillisecondsOncall
  LogsKinesisStreamArn:
    Value: !Ref LogsKinesisStreamArn
  LogsKinesisStreamKeyArn:
    Value: !Ref LogsKinesisStreamKeyArn
  ApiKeyTablesEncryptKeyId:
    Value: !Ref ApiKeyTablesEncryptKeyId
  SafestorageLoggerLogGroupName:
    Value: !Ref SafestorageLoggerLogGroupName
  VpcEgressSubnetsIds:
    Value: !If [ IsEgressDefined, !Ref VpcEgressSubnetsIds, !Ref VpcSubnets ]
  RedisServerlessArn:
    Value: !Ref RedisServerlessArn
  RedisServerlessName:
    Value: !Ref RedisServerlessName
  ElasticCacheUser1Arn:
    Value: !Ref ElasticCacheUser1Arn
    
  # Data Monitoring pass-through params
  DynamoDbExportTableNames:
    Value: !Ref DynamoDbExportTableNames
  DynamoDbExportPrefix:
    Value: !Ref DynamoDbExportPrefix
  ConfinfoDynamoDbExportBucketName:
    Value: !Ref ConfinfoDynamoDbExportBucketName
  ParquetBucketPath:
    Value: !Ref ParquetBucketPath
  DataMonitoringCodebuildComputeType:
    Value: !Ref DataMonitoringCodebuildComputeType
  DataMonitoringIndexCronExpression:
    Value: !Ref DataMonitoringIndexCronExpression
  DataMonitoringScriptVersion:
    Value: !Ref DataMonitoringScriptVersion
  DataLakeAccountId:
    Value: !Ref DataLakeAccountId1
  DataMonitoringPrototypeVersion:
    Value: !Ref DataMonitoringPrototypeVersion