AWSTemplateFormatVersion: 2010-09-09
Description: 'This template deploys the queues needed for communication between microservices and 
              API gateway custom domains'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  LogsBucketName:
    Type: String
    Description: Bucket name where the logs must be exported
  LogsExporterRoleArn:
    Type: String
    Description: ARN of the role used to write to external logs bucket

  TimelineCdcKinesisStreamArn:
    Type: String
    Description: timeline CDC kinesis stream ARN
  TimelineCdcKinesisKeyArn:
    Type: String
    Description: timeline CDC kinesis stream encryption key ARN

  NotificationCdcKinesisStreamArn:
    Type: String
    Description: notification CDC kinesis stream ARN
  NotificationCdcKinesisKeyArn:
    Type: String
    Description: notification CDC kinesis stream encryption key ARN

  MandateCdcKinesisStreamArn:
    Type: String
    Description: mandate CDC kinesis stream ARN
  MandateCdcKinesisKeyArn:
    Type: String
    Description: mandate CDC kinesis stream encryption key ARN

  UserAttributesCdcKinesisStreamArn:
    Type: String
    Description: user-attributes CDC kinesis stream ARN
  UserAttributesCdcKinesisKeyArn:
    Type: String
    Description: user-attributes CDC kinesis stream encryption key ARN


  OpenSearchClusterEndpoint:
    Type: String
    Description: HTTPS endpoint of the destination Open Search cluster
  OpenSearchIndex:
    Type: String
    Description: Index on the destination Open Search domain
  OpenSearchDeliveryVpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where Kinesis Firehose will create ENIs to reach the Open Search cluster
  OpenSearchDeliverySubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The IDs of the subnets where Kinesis Firehose will create ENIs to reach the Open Search cluster
  OpenSearchSecretArn:
    Type: String
    Description: The ARN of the secret containing OpenSearch credentials

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'
  AlarmSNSTopicArn:
    Type: String
    Description: ARN of the SNS topic for alarms

Conditions:
  HasOpenSearchExport: !Not [ !Equals [ !Ref OpenSearchClusterEndpoint, "" ] ]

Resources:

  ###             Export cloudwatch logs to Log saving bucket             ###
  ###########################################################################

  # - Delivery
  PnDeliveryEcsLogsToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/export-cloudwatch-logs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        LogsBucketName: !Ref LogsBucketName
        LogsExporterRoleArn: !Ref LogsExporterRoleArn
        StreamNamePrefix: pnDelivery
        LogGroupName: '/ecs/pn-delivery'
        RetentionTag: 'ecs'
        CloudwatchFilterPattern: ''
        StreamRetentionPeriodHours: 24

  # - Delivery Push
  PnDeliveryPushEcsLogsToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/export-cloudwatch-logs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        LogsBucketName: !Ref LogsBucketName
        LogsExporterRoleArn: !Ref LogsExporterRoleArn
        StreamNamePrefix: pnDeliveryPush
        LogGroupName: '/ecs/pn-delivery-push'
        RetentionTag: 'ecs'
        CloudwatchFilterPattern: ''
        StreamRetentionPeriodHours: 24
        StreamShardCount: 1

  # - Mandate
  PnMandateEcsLogsToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/export-cloudwatch-logs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        LogsBucketName: !Ref LogsBucketName
        LogsExporterRoleArn: !Ref LogsExporterRoleArn
        StreamNamePrefix: pnMandate
        LogGroupName: '/ecs/pn-mandate'
        RetentionTag: 'ecs'
        CloudwatchFilterPattern: ''
        StreamRetentionPeriodHours: 24

  # - User Attributes
  PnUserAttributesEcsLogsToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/export-cloudwatch-logs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        LogsBucketName: !Ref LogsBucketName
        LogsExporterRoleArn: !Ref LogsExporterRoleArn
        StreamNamePrefix: pnUserAttributes
        LogGroupName: '/ecs/pn-UserAttributes'
        RetentionTag: 'ecs'
        CloudwatchFilterPattern: ''
        StreamRetentionPeriodHours: 24

  # - External Registries
  PnExternalRegistryEcsLogsToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/export-cloudwatch-logs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        LogsBucketName: !Ref LogsBucketName
        LogsExporterRoleArn: !Ref LogsExporterRoleArn
        StreamNamePrefix: pnExternalRegistry
        LogGroupName: '/ecs/pn-ExternalRegistry'
        RetentionTag: 'ecs'
        CloudwatchFilterPattern: ''
        StreamRetentionPeriodHours: 24

  ###             Export dynamo CDC to Log saving bucket             ###
  ###########################################################################

  # Export timeline cdc to Log analysis account
  PnTimelineCdcToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-source-stream-to-logs-bucket.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        SourceKinesisDataStreamArn: !Ref TimelineCdcKinesisStreamArn
        SourceKinesisDataStreamKeyArn: !Ref TimelineCdcKinesisKeyArn
        LogsBucketName: !Ref LogsBucketName
        LogsExporterRoleArn: !Ref LogsExporterRoleArn
        StreamNamePrefix: pnTimelineCdc

  # Export notification cdc to Log analysis account
  PnNotificationCdcToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-source-stream-to-logs-bucket.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        SourceKinesisDataStreamArn: !Ref NotificationCdcKinesisStreamArn
        SourceKinesisDataStreamKeyArn: !Ref NotificationCdcKinesisKeyArn
        LogsBucketName: !Ref LogsBucketName
        LogsExporterRoleArn: !Ref LogsExporterRoleArn
        StreamNamePrefix: pnNotificationCdc

  # Export mandate cdc to Log analysis account
  PnMandateCdcToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-source-stream-to-logs-bucket.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        SourceKinesisDataStreamArn: !Ref MandateCdcKinesisStreamArn
        SourceKinesisDataStreamKeyArn: !Ref MandateCdcKinesisKeyArn
        LogsBucketName: !Ref LogsBucketName
        LogsExporterRoleArn: !Ref LogsExporterRoleArn
        StreamNamePrefix: pnMandateCdc

  # Export user-attributes cdc to Log analysis account
  PnUserAttributesCdcToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-source-stream-to-logs-bucket.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        SourceKinesisDataStreamArn: !Ref UserAttributesCdcKinesisStreamArn
        SourceKinesisDataStreamKeyArn: !Ref UserAttributesCdcKinesisKeyArn
        LogsBucketName: !Ref LogsBucketName
        LogsExporterRoleArn: !Ref LogsExporterRoleArn
        StreamNamePrefix: pnUserAttributesCdc


  ###             Export cloudwatch logs to OpenSearch                    ###
  ###########################################################################

  PnDeliveryEcsLogsToOpenSearch:
    Condition: HasOpenSearchExport
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/logs-delivery-opensearch.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        StreamNamePrefix: pnDelivery
        KinesisStreamArn: !GetAtt PnDeliveryEcsLogsToExternalBucket.Outputs.KinesisStreamArn
        KinesisStreamKMSKeyArn: !GetAtt PnDeliveryEcsLogsToExternalBucket.Outputs.KinesisStreamKMSKeyArn
        OpenSearchClusterEndpoint: !Ref OpenSearchClusterEndpoint
        OpenSearchIndex: !Ref OpenSearchIndex
        OpenSearchDeliveryVpcId: !Ref OpenSearchDeliveryVpcId
        OpenSearchDeliverySubnetIds: !Join [",", !Ref OpenSearchDeliverySubnetIds]
        OpenSearchSecretArn: !Ref OpenSearchSecretArn
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  PnDeliveryPushEcsLogsToOpenSearch:
    Condition: HasOpenSearchExport
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/logs-delivery-opensearch.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        StreamNamePrefix: pnDeliveryPush
        KinesisStreamArn: !GetAtt PnDeliveryPushEcsLogsToExternalBucket.Outputs.KinesisStreamArn
        KinesisStreamKMSKeyArn: !GetAtt PnDeliveryPushEcsLogsToExternalBucket.Outputs.KinesisStreamKMSKeyArn
        OpenSearchClusterEndpoint: !Ref OpenSearchClusterEndpoint
        OpenSearchIndex: !Ref OpenSearchIndex
        OpenSearchDeliveryVpcId: !Ref OpenSearchDeliveryVpcId
        OpenSearchDeliverySubnetIds: !Join [",", !Ref OpenSearchDeliverySubnetIds]
        OpenSearchSecretArn: !Ref OpenSearchSecretArn
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  PnMandateEcsLogsToOpenSearch:
    Condition: HasOpenSearchExport
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/logs-delivery-opensearch.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        StreamNamePrefix: pnMandate
        KinesisStreamArn: !GetAtt PnMandateEcsLogsToExternalBucket.Outputs.KinesisStreamArn
        KinesisStreamKMSKeyArn: !GetAtt PnMandateEcsLogsToExternalBucket.Outputs.KinesisStreamKMSKeyArn
        OpenSearchClusterEndpoint: !Ref OpenSearchClusterEndpoint
        OpenSearchIndex: !Ref OpenSearchIndex
        OpenSearchDeliveryVpcId: !Ref OpenSearchDeliveryVpcId
        OpenSearchDeliverySubnetIds: !Join [",", !Ref OpenSearchDeliverySubnetIds]
        OpenSearchSecretArn: !Ref OpenSearchSecretArn
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  PnUserAttributesEcsLogsToOpenSearch:
    Condition: HasOpenSearchExport
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/logs-delivery-opensearch.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        StreamNamePrefix: pnUserAttributes
        KinesisStreamArn: !GetAtt PnUserAttributesEcsLogsToExternalBucket.Outputs.KinesisStreamArn
        KinesisStreamKMSKeyArn: !GetAtt PnUserAttributesEcsLogsToExternalBucket.Outputs.KinesisStreamKMSKeyArn
        OpenSearchClusterEndpoint: !Ref OpenSearchClusterEndpoint
        OpenSearchIndex: !Ref OpenSearchIndex
        OpenSearchDeliveryVpcId: !Ref OpenSearchDeliveryVpcId
        OpenSearchDeliverySubnetIds: !Join [",", !Ref OpenSearchDeliverySubnetIds]
        OpenSearchSecretArn: !Ref OpenSearchSecretArn
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  PnExternalRegistryEcsLogsToOpenSearch:
    Condition: HasOpenSearchExport
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/logs-delivery-opensearch.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        StreamNamePrefix: pnExternalRegistry
        KinesisStreamArn: !GetAtt PnExternalRegistryEcsLogsToExternalBucket.Outputs.KinesisStreamArn
        KinesisStreamKMSKeyArn: !GetAtt PnExternalRegistryEcsLogsToExternalBucket.Outputs.KinesisStreamKMSKeyArn
        OpenSearchClusterEndpoint: !Ref OpenSearchClusterEndpoint
        OpenSearchIndex: !Ref OpenSearchIndex
        OpenSearchDeliveryVpcId: !Ref OpenSearchDeliveryVpcId
        OpenSearchDeliverySubnetIds: !Join [",", !Ref OpenSearchDeliverySubnetIds]
        OpenSearchSecretArn: !Ref OpenSearchSecretArn
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  PnMandateCdcToOpenSearch:
    Condition: HasOpenSearchExport
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/logs-delivery-opensearch.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        StreamNamePrefix: pnMandateCdc
        KinesisStreamArn: !Ref MandateCdcKinesisStreamArn
        KinesisStreamKMSKeyArn: !Ref MandateCdcKinesisKeyArn
        OpenSearchClusterEndpoint: !Ref OpenSearchClusterEndpoint
        OpenSearchIndex: !Ref OpenSearchIndex
        OpenSearchDeliveryVpcId: !Ref OpenSearchDeliveryVpcId
        OpenSearchDeliverySubnetIds: !Join [",", !Ref OpenSearchDeliverySubnetIds]
        OpenSearchSecretArn: !Ref OpenSearchSecretArn
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  PnUserAttributesCdcToOpenSearch:
    Condition: HasOpenSearchExport
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/logs-delivery-opensearch.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        StreamNamePrefix: pnUserAttributesCdC
        KinesisStreamArn: !Ref UserAttributesCdcKinesisStreamArn
        KinesisStreamKMSKeyArn: !Ref UserAttributesCdcKinesisKeyArn
        OpenSearchClusterEndpoint: !Ref OpenSearchClusterEndpoint
        OpenSearchIndex: !Ref OpenSearchIndex
        OpenSearchDeliveryVpcId: !Ref OpenSearchDeliveryVpcId
        OpenSearchDeliverySubnetIds: !Join [",", !Ref OpenSearchDeliverySubnetIds]
        OpenSearchSecretArn: !Ref OpenSearchSecretArn
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  PnTimelineCdcToOpenSearch:
    Condition: HasOpenSearchExport
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/logs-delivery-opensearch.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        StreamNamePrefix: pnTimelineCdc
        KinesisStreamArn: !Ref TimelineCdcKinesisStreamArn
        KinesisStreamKMSKeyArn: !Ref TimelineCdcKinesisKeyArn
        OpenSearchClusterEndpoint: !Ref OpenSearchClusterEndpoint
        OpenSearchIndex: !Ref OpenSearchIndex
        OpenSearchDeliveryVpcId: !Ref OpenSearchDeliveryVpcId
        OpenSearchDeliverySubnetIds: !Join [",", !Ref OpenSearchDeliverySubnetIds]
        OpenSearchSecretArn: !Ref OpenSearchSecretArn
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  PnNotificationCdcToOpenSearch:
    Condition: HasOpenSearchExport
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/logs-delivery-opensearch.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        StreamNamePrefix: pnNotificationCdc
        KinesisStreamArn: !Ref NotificationCdcKinesisStreamArn
        KinesisStreamKMSKeyArn: !Ref NotificationCdcKinesisKeyArn
        OpenSearchClusterEndpoint: !Ref OpenSearchClusterEndpoint
        OpenSearchIndex: !Ref OpenSearchIndex
        OpenSearchDeliveryVpcId: !Ref OpenSearchDeliveryVpcId
        OpenSearchDeliverySubnetIds: !Join [",", !Ref OpenSearchDeliverySubnetIds]
        OpenSearchSecretArn: !Ref OpenSearchSecretArn
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
