AWSTemplateFormatVersion: 2010-09-09
Description: 'This template deploys the queues needed for monitoring'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of the SNS topic for alarms

  LogsKinesisSourceStreamArn:
    Default: ''
    Type: String
    Description: where to send logs

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  LambdasBucketName:
    Type: String

  LambdasBasePath:
    Type: String

  EnvironmentType:
    Type: String
    Default: ''

  CompositeMetricGeneratorScheduleExpression:
    Type: String
    Default: 'rate(10 minutes)'

  HelpdeskAccountId:
    Type: String
    Default: ''
    Description: 'Helpdesk account ID'

  ConfidentialInfoAccountId:
    Type: String
    Default: ''
    Description: 'ConfidentialInfo account ID'

  LogsKinesisSourceStreamName:
    Type: String
    Default: ''
    Description: 'Kinesis stream name to send logs to'

  CdcKinesisSourceStreamName:
    Type: String
    Default: ''
    Description: 'Kinesis stream name to send CDC logs to'

  LogsKinesisMaxAgeInMilliseconds:
    Type: Number
    Description: 'MaxAgeInMilliseconds for Kinesis Logs GetRecords'

  CdcKinesisMaxAgeInMilliseconds:
    Type: Number
    Description: 'MaxAgeInMilliseconds for Kinesis Cdc GetRecords'

  LogsKinesisMaxAgeInMillisecondsOncall:
    Type: Number
    Description: 'MaxAgeInMilliseconds for Kinesis Logs GetRecords (oncall)'

  CdcKinesisMaxAgeInMillisecondsOncall:
    Type: Number
    Description: 'MaxAgeInMilliseconds for Kinesis Cdc GetRecords (oncall)'

  LogsBucketName:
    Type: String
    Description: 'Name of the bucket where logs are stored'
Conditions:
  SendLogToKinesis: !Not [ !Equals [ !Ref LogsKinesisSourceStreamArn, '' ] ]

Resources:
 ###                            Event adn Alarm                           ###
  ############################################################################

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${ProjectName}-ECSOutOfMemoryStoppedTasksEvent"
      Description: Triggered when an Amazon ECS Task is stopped due to OOM
      EventPattern:
        source:
          - aws.ecs
        detail-type:
          - ECS Task State Change
        detail:
          desiredStatus:
            - STOPPED
          lastStatus:
            - STOPPED
          containers:
            reason:
              - prefix: "OutOfMemory"
      State: ENABLED
      Targets:
        - Arn: !GetAtt LogGroupOOMEvents.Arn
          Id: LogTarget
    
  StoppedTaskEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${ProjectName}-StoppedTasksEventRule"
      Description: Triggered when an Amazon ECS Task is stopped
      EventPattern:
        source:
          - aws.ecs
        detail-type:
          - ECS Task State Change
        detail:
          desiredStatus:
            - STOPPED
          lastStatus:
            - STOPPED
      State: ENABLED
      Targets:
        - Arn: !GetAtt LogGroupTaskStoppedEvents.Arn
          Id: LogTarget

  # Creating a log group for monitoring the OOM events
  LogGroupTaskStoppedEvents:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/events/${ProjectName}-ecs-stopped-events"
      RetentionInDays: 90

  # Creating a log group for monitoring the OOM events
  LogGroupOOMEvents:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/events/${ProjectName}-ecs-oom-errors"
      RetentionInDays: 90

  # Resource based policy to allow EventBridge to publish to CloudWatch Logs
  LogGroupOOMEventsPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: !Sub "${ProjectName}-EventBridgeToCWLogsPolicy"
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "EventBridgetoCWLogsCreateLogStreamPolicy",
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "events.amazonaws.com"
                ]
              },
              "Action": [
                "logs:CreateLogStream"
              ],
              "Resource": [
                "${LogGroupOOMEvents.Arn}",
                "${LogGroupTaskStoppedEvents.Arn}"
              ]
            },
            {
              "Sid": "EventBridgetoCWLogsPutLogEventsPolicy",
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "events.amazonaws.com"
                ]
              },
              "Action": [
                "logs:PutLogEvents"
              ],
              "Resource": [
                "${LogGroupOOMEvents.Arn}",
                "${LogGroupTaskStoppedEvents.Arn}"
              ],
              "Condition": {
                "ArnEquals": {"AWS:SourceArn": "${EventRule.Arn}"}
              }
            }
          ]
        }

  # CloudWatch metric: it is exepcted to be a very rare event so it is acceptable to have one metric for all containers
  # Note: the container that runs out of memory is detailed in the log event
  OutOfMemoryLogsMetricFilter: 
    Type: AWS::Logs::MetricFilter
    Properties: 
      LogGroupName: !Ref LogGroupOOMEvents
      FilterPattern: ' '
      MetricTransformations: 
        - MetricValue: 1
          MetricNamespace: "OutOfMemoryErrors"
          MetricName: !Sub "${ProjectName}-ECSOutOfMemory"

  CloudWatchAlarmOOM:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-ECSOutOfMemory-Alarm"
      AlarmDescription: "CloudWatch alarm for when ECS task stop with OOM errors."
      TreatMissingData: notBreaching        
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: 1            
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Namespace: OutOfMemoryErrors   
      MetricName: !Sub "${ProjectName}-ECSOutOfMemory"
      Statistic: Sum
      Threshold: 1
 
  SubscriptionFilterServiceRole:
    Condition: SendLogToKinesis
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: logs.amazonaws.com
        Version: "2012-10-17"
      Path: /
      Policies:
        -
          PolicyName: !Sub '${ProjectName}-monitoring-subscription-role'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - kinesis:PutRecord
                Effect: Allow
                Resource: "*"
              - Action:
                - "kms:Encrypt"
                - "kms:GenerateDataKey"
                - "kms:Decrypt"
                Effect: Allow
                Resource: "*"

  OomSubscriptionFilter:
    Condition: SendLogToKinesis
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn:
        Fn::GetAtt:
          - "SubscriptionFilterServiceRole"
          - "Arn"
      LogGroupName: !Ref LogGroupOOMEvents
      FilterPattern: ' '
      DestinationArn: !Ref LogsKinesisSourceStreamArn

  ###                           Alarm State ChangeRule                    ###
  ###########################################################################
  # EVENT BRIDGE RULE: invoke lambda on alarm state change

  DefaultEventBusMonitoringLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CompositeMetricGenerator.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SendAlarmChangeEventsToLambda.Arn

  DefaultEventBusScheduleMonitoringLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CompositeMetricGenerator.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CompositeMetricGeneratorScheduleRule.Arn

  SendAlarmChangeEventsToLambda:
    Type: AWS::Events::Rule
    Properties: 
      Description: Save build events
      RoleArn: !GetAtt "MonitoringBusExecuteLambdaRole.Arn"
      EventPattern: 
        source: [ "aws.cloudwatch" ]
        detail-type: ["CloudWatch Alarm State Change"]
      Targets: 
        - Arn: !GetAtt CompositeMetricGenerator.Arn
          Id: !Sub ${ProjectName}-AlarmStateChangeTarget
        - Arn: !Ref AlarmSNSTopicArn
          InputPath: $.detail
          Id: !Sub ${ProjectName}-AlarmSnsTopic

  # - Role and policy used to execute lambda from EventBridge rule
  MonitoringBusExecuteLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyName: !Sub ${ProjectName}-monitoring-bus-policy
          PolicyDocument:
            Statement:
              - Sid: executeLambda
                Action:
                  - lambda:InvokeFunction
                  - lambda:InvokeAsync
                Effect: Allow
                Resource: 
                  - !GetAtt CompositeMetricGenerator.Arn

  CompositeMetricGeneratorScheduleRule:
    Type: AWS::Events::Rule
    Properties: 
      Name: !Sub "${ProjectName}-CompositeMetricGeneratorScheduleRule"
      ScheduleExpression: !Ref CompositeMetricGeneratorScheduleExpression
      State: ENABLED
      Targets: 
        - Arn: !GetAtt CompositeMetricGenerator.Arn
          Id: !Ref CompositeMetricGenerator
          
  ### Alarm state change lambda               ####
  ################################################
  # Lambda function
  CompositeMetricGenerator:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-compositeMetricGenerator"
      Runtime: nodejs18.x
      Handler: "index.handler"
      Code:
        S3Bucket: !Ref LambdasBucketName
        S3Key: !Sub "${LambdasBasePath}/composite-metric-generator.zip"
      Role: !GetAtt CompositeMetricGeneratorRole.Arn
      TracingConfig:
        Mode: Active
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:339249233099:layer:LambdaInsightsExtension:13"
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          ENVIRONMENT_TYPE: !Ref EnvironmentType
          ACCOUNT_ID: !Sub ${AWS::AccountId}
          HELPDESK_ACCOUNT_ID: !Ref HelpdeskAccountId
          CONFIDENTIAL_INFO_ACCOUNT_ID: !Ref ConfidentialInfoAccountId
      Timeout : 180

  # Lambda function role
  CompositeMetricGeneratorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-compositeMetricGeneratorRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        # - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
        # - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Path: /

  # Lambda function IAM policy
  CompositeMetricGeneratorRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ProjectName}-compositeMetricGeneratorRolePolicy
      Roles:
        - !Ref CompositeMetricGeneratorRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "cloudwatch:*"
            Resource: '*' # cannot restrict because it needs to read metrics and alarms of multiple AWS accounts and regions
          - Effect: Allow
            Action:
              - "sts:AssumeRole"
            Resource: 
              - !Sub "arn:aws:iam::${HelpdeskAccountId}:role/CloudWatch-CrossAccountSharingRole"
              - !Sub "arn:aws:iam::${ConfidentialInfoAccountId}:role/CloudWatch-CrossAccountSharingRole"

  # lambda function Log Group
  CompositeMetricGeneratorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CompositeMetricGenerator}"
      RetentionInDays: 14

  CompositeMetricGeneratorAlarm:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CompositeMetricGeneratorLogGroup
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/lambda-alarms.yaml"
      Parameters:
        FunctionName: !Ref CompositeMetricGenerator
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  # Logs Kinesis GetRecords.IteratorAgeMilliseconds alarm
  LogsKinesisGetRecordsIteratorAgeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-LogsKinesis-IteratorAge-Alarm"
      AlarmDescription: "CloudWatch alarm for when Kinesis Logs GetRecords.IteratorAgeMilliseconds is too high."
      TreatMissingData: notBreaching        
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      Dimensions:
        - Value: !Ref LogsKinesisSourceStreamName
          Name: StreamName        
      DatapointsToAlarm: 10            
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Namespace: AWS/Kinesis   
      MetricName: GetRecords.IteratorAgeMilliseconds
      Statistic: Maximum
      Threshold: !Ref LogsKinesisMaxAgeInMilliseconds

  OncallLogsKinesisGetRecordsIteratorAgeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "oncall-${ProjectName}-LogsKinesis-IteratorAge-Alarm"
      AlarmDescription: "CloudWatch alarm for when Kinesis Logs GetRecords.IteratorAgeMilliseconds is too high."
      TreatMissingData: notBreaching        
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      Dimensions:
        - Value: !Ref LogsKinesisSourceStreamName
          Name: StreamName        
      DatapointsToAlarm: 10            
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Namespace: AWS/Kinesis   
      MetricName: GetRecords.IteratorAgeMilliseconds
      Statistic: Maximum
      Threshold: !Ref LogsKinesisMaxAgeInMillisecondsOncall

  # Cdc Kinesis GetRecords.IteratorAgeMilliseconds alarm
  CdcKinesisGetRecordsIteratorAgeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-CdcKinesis-IteratorAge-Alarm"
      AlarmDescription: "CloudWatch alarm for when Kinesis Cdc GetRecords.IteratorAgeMilliseconds is too high."
      TreatMissingData: notBreaching        
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      Dimensions:
        - Value: !Ref CdcKinesisSourceStreamName
          Name: StreamName
      DatapointsToAlarm: 10           
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Namespace: AWS/Kinesis   
      MetricName: GetRecords.IteratorAgeMilliseconds
      Statistic: Maximum
      Threshold: !Ref CdcKinesisMaxAgeInMilliseconds

  OncallCdcKinesisGetRecordsIteratorAgeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "oncall-${ProjectName}-CdcKinesis-IteratorAge-Alarm"
      AlarmDescription: "CloudWatch alarm for when Kinesis Cdc GetRecords.IteratorAgeMilliseconds is too high."
      TreatMissingData: notBreaching        
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      Dimensions:
        - Value: !Ref CdcKinesisSourceStreamName
          Name: StreamName
      DatapointsToAlarm: 10           
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Namespace: AWS/Kinesis   
      MetricName: GetRecords.IteratorAgeMilliseconds
      Statistic: Maximum
      Threshold: !Ref CdcKinesisMaxAgeInMillisecondsOncall

  ClockErrorBoundAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "pn-Clock-Error-Bound-Alarm"
      AlarmDescription: "CloudWatch Alarm for Clock Error Bound limit over threshold"
      TreatMissingData: notBreaching       
      Metrics:
        - Id: q1
          Expression: "SELECT MAX(ClockErrorBound) FROM SCHEMA(\"ECS/ContainerInsights\", ClusterName,Family,TaskID) WHERE ClusterName = 'pn-core-ecs-cluster' GROUP BY ClusterName"
          Period: 600
          ReturnData: False
        - Id: e2
          Expression: "IF(MAX(q1) < 100, 0, 1)"
          Period: 600
      DatapointsToAlarm: 2           
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      Threshold: 1
  
  SynchronizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "pn-Synchronization-Alarm"
      AlarmDescription: "CloudWatch Alarm for Synchronization value different by Synchronized"
      TreatMissingData: notBreaching       
      Metrics:
        - Id: q1
          Expression: "SELECT MAX(Synchronization) FROM SCHEMA(\"ECS/ContainerInsights\", ClusterName,Family,TaskID) WHERE ClusterName = 'pn-core-ecs-cluster' GROUP BY ClusterName"
          Period: 600
          ReturnData: False
        - Id: e2
          Expression: "IF(MAX(q1) < 1, 0, 1)"
          Period: 600
      DatapointsToAlarm: 2           
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      Threshold: 1

  # Trail 
  DiagnosticLambdaCloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: pn-DiagnosticLambdaCloudTrail
      IsMultiRegionTrail: false
      IsOrganizationTrail: false
      EnableLogFileValidation: false
      AdvancedEventSelectors:
        - Name: diagnostic-lambda-selector
          FieldSelectors:
            - Field: "eventSource"
              Equals: 
                - "lambda.amazonaws.com"
            - Field: "eventName"
              Equals: 
                - "Invoke"
            - Field: "resources.ARN"
              StartsWith: 
                - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:diagnostic"
      S3BucketName: !Ref LogsBucketName
      S3KeyPrefix: "cloudtrail/diagnostic"
      IsLogging: true

Outputs:
  OOMAlarmArn:
    Value: !GetAtt CloudWatchAlarmOOM.Arn
    Description: 'ARN of cloudwatch out of memory alarm'

  LogsKinesisGetRecordsIteratorAgeAlarmArn:
    Value: !GetAtt LogsKinesisGetRecordsIteratorAgeAlarm.Arn

  CdcKinesisGetRecordsIteratorAgeAlarmArn:
    Value: !GetAtt CdcKinesisGetRecordsIteratorAgeAlarm.Arn

  CompositeMetricGeneratorAlarmArn: 
    Value: !GetAtt CompositeMetricGeneratorAlarm.Outputs.LambdaInvocationErrorLogsMetricAlarm
    Description: 'ARN of composite metric generator alarm'

  
  DiagnosticTrailArn:
    Value: !GetAtt DiagnosticLambdaCloudTrail.Arn
    Description: 'ARN of diagnostic lambda cloudtrail'