AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of OpenSearch

Parameters:
  EbsIops:
    Type: Number
    Description: The number of I/O operations per second (IOPS) that the volume supports
  
  EbsThroughput:
    Type: Number
    Description: The throughput (in MiB/s) of the EBS volumes attached to data nodes

  EbsVolumeSize:
    Type: Number
    Description: The size (in GiB) of the EBS volume for each data node

  EbsVolumeType:
    Type: String
    Description: The EBS volume type to use with the OpenSearch Service domain, such as standard, gp2, or io1

  EngineVersion:
    Type: String
    Description: User-defined OpenSearch version

  InstanceReplicas:
    Type: Number
    Default: 3
    Description: Number of instances

  InstanceType:
    Type: String
    Description: "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html"

  MasterNodeType:
    Type: String
    Description: "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html Master Node Instance Type"
    Default: ""
    
  MasterNodeInstancesNumber:
    Type: Number
    Description: "Master Node Instance number"

  ProjectName:
    Type: String
    Description: Name of the project

  VpcOpensearchSubnetsIds:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: Private subnets to deploy resources into

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: VPC id of the subnets

  # Pass through
  OpenSearchSecretArn:
    Type: String
    Description: Lambda logs ingestion param

  ZoneAwareness:
    Type: String
    Default: true
    Description: Zone Awareness Enabled
    AllowedValues:
      - true
      - false

  WarmCount:
    Type: Number
    Default: 3
    Description: Number of warm nodes

  WarmEnabled:
    Type: String
    Default: false
    Description: Warm nodes enabled
    AllowedValues:
      - true
      - false

  WarmType:
    Type: String
    Description: "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html Warm Node Instance Type"
    Default: "ultrawarm1.medium.search"

Conditions:
  HasDedicatedMaster: !Not [ !Equals [ !Ref MasterNodeType, "" ] ]
  HasZoneAwareness: !Equals [ !Ref ZoneAwareness, true ]
  HasWarmEnabled: !Equals [ !Ref WarmEnabled, true ]

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Open HTTPS port
      GroupName: !Sub ${ProjectName}-opensearch
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId: !Ref VpcId

  ### AWS KMS / Server-side encryption for Kinesis Stream 
  # https://docs.aws.amazon.com/streams/latest/dev/server-side-encryption.html
  OpenSearchEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  OpenSearchServiceDomain:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      AccessPolicies:
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:ESHttp*"
            Resource: "*"
        Version: "2012-10-17"
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: !GetAtt OpenSearchEncryptionKey.KeyId
      NodeToNodeEncryptionOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: "Policy-Min-TLS-1-2-PFS-2023-10"
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions: 
          MasterUserName: !Sub '{{resolve:secretsmanager:${ProjectName}-opensearch-master:SecretString:username}}'
          MasterUserPassword: !Sub '{{resolve:secretsmanager:${ProjectName}-opensearch-master:SecretString:password}}'
      ClusterConfig: !If
        - HasDedicatedMaster
        - !If
            - HasZoneAwareness
            - 
              InstanceCount: !Ref InstanceReplicas
              InstanceType: !Ref InstanceType
              DedicatedMasterCount: !Ref MasterNodeInstancesNumber
              DedicatedMasterEnabled: true
              DedicatedMasterType: !Ref MasterNodeType
              ZoneAwarenessEnabled: !Ref ZoneAwareness
              ZoneAwarenessConfig:
                AvailabilityZoneCount: 3
              WarmEnabled: !Ref WarmEnabled
              WarmCount: !If
                - HasWarmEnabled
                - !Ref WarmCount
                - !Ref AWS::NoValue
              WarmType: !If
                - HasWarmEnabled
                - !Ref WarmType
                - !Ref AWS::NoValue
            - 
              InstanceCount: !Ref InstanceReplicas
              InstanceType: !Ref InstanceType
              DedicatedMasterCount: !Ref MasterNodeInstancesNumber
              DedicatedMasterEnabled: true
              DedicatedMasterType: !Ref MasterNodeType
              ZoneAwarenessEnabled: !Ref ZoneAwareness
              WarmEnabled: !Ref WarmEnabled
              WarmCount: !If
                - HasWarmEnabled
                - !Ref WarmCount
                - !Ref AWS::NoValue
              WarmType: !If
                - HasWarmEnabled
                - !Ref WarmType
                - !Ref AWS::NoValue
        - !If
            - HasZoneAwareness
            - 
              InstanceCount: !Ref InstanceReplicas
              InstanceType: !Ref InstanceType
              DedicatedMasterEnabled: false
              ZoneAwarenessEnabled: !Ref ZoneAwareness
              ZoneAwarenessConfig:
                AvailabilityZoneCount: 3
            -
              InstanceCount: !Ref InstanceReplicas
              InstanceType: !Ref InstanceType
              DedicatedMasterEnabled: false
              ZoneAwarenessEnabled: !Ref ZoneAwareness
      EBSOptions:
        EBSEnabled: true
        Iops: !Ref EbsIops
        Throughput: !Ref EbsThroughput
        VolumeSize: !Ref EbsVolumeSize
        VolumeType: !Ref EbsVolumeType
      EngineVersion: !Ref EngineVersion
      VPCOptions: !If
        - HasZoneAwareness
        -
          SecurityGroupIds:
            - Ref: SecurityGroup
          SubnetIds: !Ref VpcOpensearchSubnetsIds
        -
          SecurityGroupIds:
            - Ref: SecurityGroup
          SubnetIds: 
            - !Select [0, !Ref VpcOpensearchSubnetsIds] 
      Tags:
        - Key: "pn-eni-related"
          Value: "true"
        - Key: "pn-eni-related-groupName-regexp"
          Value: !Base64 "^pn-opensearch.*$"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

Outputs:
  ClusterName:
    Description: The name of the OpenSearch Service domain
    Value: !Ref OpenSearchServiceDomain

  DomainEndpoint:
    Value: !GetAtt OpenSearchServiceDomain.DomainEndpoint

  DomainArn:
    Value: !GetAtt OpenSearchServiceDomain.Arn

  OpenSearchSecretArn:
    Value: !Ref OpenSearchSecretArn

  OpenSearchClusterEndpoint:
    Value: !GetAtt OpenSearchServiceDomain.DomainEndpoint