---
AWSTemplateFormatVersion: 2010-09-09


Description: >
  This template deploys the base infra for PN
Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione
  VpcNumber:
    Type: String
    Description: Second byte from the left for VPC CIDR

  TemplateBucketBaseUrl:
    Type: String
    Description: >
      The S3 bucket from which to fetch the templates used by this stack.

Resources:

  ###                       VPC BASE CONFIGURATIONS                       ###
  ###########################################################################

  # VPC and subnets
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/vpc.yaml"
      Parameters:
        VpcName: !Ref ProjectName
        VpcNumber: !Ref VpcNumber

  # Private connection from subnets to AWS services
  VPCEndpoints:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/vpc-endpoints.yaml"
      Parameters:
        VpcName: !Ref ProjectName
        VpcNumber: !Ref VpcNumber
        Subnets: !GetAtt VPC.Outputs.PublicSubnetsIds
        RouteTableIds: !GetAtt VPC.Outputs.PublicRouteTables
        VpcId: !GetAtt VPC.Outputs.VpcId

  # LoadBalancer
  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/load-balancer.yaml"
      Parameters:
        LoadBalancerName: !Ref ProjectName
        Subnets: !GetAtt VPC.Outputs.PublicSubnetsIds
        VpcId: !GetAtt VPC.Outputs.VpcId

  ###                             ECS CLUSTER                             ###
  ###########################################################################
  #
  ECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-cluster.yaml"
      Parameters:
        MacroServiceName: !Sub '${ProjectName}-core'









  ###                     MESSAGE ORIENTED MIDDLEWARE                     ###
  ###########################################################################

  ### SQS ###
  DeliveryPushInputsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_inputs'
        DelaySeconds: 1

  DeliveryPushActionsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_actions'
        DelaySeconds: 1

  ExternalChannelsInputsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-external_channel_inputs'
        DelaySeconds: 1

  ExternalChannelsOutputsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-external_channel_outputs'
        DelaySeconds: 1

  ExternalChannelsElabResQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-external_channel_elab_res'
        DelaySeconds: 1

  DeliveryPushActionsDoneQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_actions-done'
        DelaySeconds: 2


