AWSTemplateFormatVersion: 2010-09-09
Description: 'This template deploys the queues needed for comuication between microservices and 
              API gateway custom domains'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ApiDnsName:
    Type: String
    Description: 'The DNS name used for B2B rest API.'

  ApiCertificateArn:
    Type: String
    Description: 'The certificate used for B2B rest API.'

  WebApiDnsName:
    Type: String
    Description: 'The DNS name used for browser rest API.'

  WebApiCertificateArn:
    Type: String
    Description: 'The certificate used for browser rest API.'

  IoApiDnsName:
    Type: String
    Description: 'The DNS name used for IO API rest'

  IoApiCertificateArn:
    Type: String
    Description: 'The certificate used for browser rest IO API.'

  HostedZoneId:
    Description: "Hosted Zone Id in which you want to add record"
    Type: String
  
  SafeStorageAccountId:
    Description: "SafeStorage AWS Account id. Useful to grant rights to send feedback to EventBus"
    Type: String

  EventBusDeadLetterQueueMaximumRetentionPeriod:
    Type: Number
    Description: "The number of seconds that Amazon SQS retains a message. You can specify an integer 
      value from 60 seconds (1 minute) to 1,209,600 seconds (14 days)."

  # pass-though parameters
  NetworkLoadBalancerLink:
    Type: String
  ApplicationLoadBalancerListenerArn:
    Type: String
  ApplicationLoadBalancerDomain:
    Type: String
  AlarmSNSTopicArn:
    Type: String
  AlarmSNSTopicName:
    Type: String
  VpcId:
    Type: String
  SubnetsIds:
    Type: String
  ECSClusterName:
    Type: String


Resources:

  ###            COMMON RESOURCES FOR WEB API AND DISTRIBUTIONS            ###
  ############################################################################

  # Custom domain for B2B api
  ApiCustomDomain:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-custom-domain.yaml"
      Parameters:
        DnsName: !Ref ApiDnsName
        CertificateArn: !Ref ApiCertificateArn
        HostedZoneId: !Ref HostedZoneId

  # Custom domain for B2B api
  WebApiCustomDomain:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-custom-domain.yaml"
      Parameters:
        DnsName: !Ref WebApiDnsName
        CertificateArn: !Ref WebApiCertificateArn
        HostedZoneId: !Ref HostedZoneId

  # Custom domain for IO api
  IoApiCustomDomain:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-custom-domain.yaml"
      Parameters:
        DnsName: !Ref IoApiDnsName
        CertificateArn: !Ref IoApiCertificateArn
        HostedZoneId: !Ref HostedZoneId

  ###                  KINESIS SOURCE STREAM FOR DYNAMO                   ###
  ###########################################################################
  TimelineCdcKinesis:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-stream.yaml"
      Parameters:
        StreamName: !Sub '${ProjectName}-timeline-cdc-stream'
        StreamRetentionPeriodHours: 24
        StreamShardCount: 10
  
  NotificationCdcKinesis:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-stream.yaml"
      Parameters:
        StreamName: !Sub '${ProjectName}-notification-cdc-stream'
        StreamRetentionPeriodHours: 24
        StreamShardCount: 10
  

  ###                    QUEUES BETWEEN MICRO SERVICES                    ###
  ###########################################################################

  ### Communication FROM SafeStorage TO pn-delivery-push ###
  SafeStorageToDeliveryPushQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-safestore_to_deliverypush'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName

  ### Communication between PN-DELIVERY and PN-DELIVERY-PUSH ###
  DeliveryPushInputsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_inputs'
        DelaySeconds: 10
        AlarmSNSTopicName: !Ref AlarmSNSTopicName


  ### Communication TO and FROM EXTERNAL-CHANNELS ###
  ExternalChannelsInputsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-external_channel_inputs'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName

  ExternalChannelsOutputsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-external_channel_outputs'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
  
  ExternalChannels2UserAttributesQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-external_channel_to_user_attributes'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName

  ###                          PN-CORE EVENT BUS                          ###
  ###########################################################################
  # Receive events from SafeStorage and CarrierPigeon (AKA ExternalChannel) 
  # and redirect to the right SQS queue
  PnCoreEventBus:
    Type: AWS::Events::EventBus
    Properties: 
      Name: !Sub '${ProjectName}-CoreEventBus'
  
  # Allow access from partner system
  PnCoreEventBusSafeStoreAccessPolicy: 
    Type: AWS::Events::EventBusPolicy
    Properties: 
      EventBusName: !Ref PnCoreEventBus
      StatementId: "AllowEventPutBySafeStorage"
      Statement: 
        Effect: "Allow"
        Principal: 
            AWS: !Sub "arn:aws:iam::${SafeStorageAccountId}:root"
        Action: "events:PutEvents"
        Resource: !GetAtt "PnCoreEventBus.Arn"
  
  # Send All Safe Storage Response to pn-delivery-push
  PnCoreEventBusToSafeStorageResponseQueue:
    Type: AWS::Events::Rule
    Properties: 
      Description: Route SafeStorage Events to pn-delivery-push
      EventBusName: !Ref PnCoreEventBus
      EventPattern:
        detail-type: [ "SafeStorageOutcomeEvent" ]
      Targets: 
        - Id: !Sub '${ProjectName}-CoreEventBus-SafeStore2DeliveryPush'
          Arn: !GetAtt SafeStorageToDeliveryPushQueue.Outputs.QueueARN
          InputPath: $.detail
          DeadLetterConfig: 
            Arn: !GetAtt EventBusDeadLetterQueue.Arn

  # Send ExternalChannel Response to pn-delivery-push
  PnCoreEventBusToExtChResponseQueue:
    Type: AWS::Events::Rule
    Properties: 
      Description: Route ExternalChannel Events to pn-delivery-push
      EventBusName: !Ref PnCoreEventBus
      EventPattern:
        detail-type: [ "ExternalChannelOutcomeEvent" ]
        details:
          clientId: [ "pn-delivery-push" ]
      Targets: 
        - Id: !Sub '${ProjectName}-CoreEventBus-ExtCh2DeliveryPush'
          Arn: !GetAtt ExternalChannelsOutputsQueue.Outputs.QueueARN
          DeadLetterConfig: 
            Arn: !GetAtt EventBusDeadLetterQueue.Arn
  
  # Send ExternalChannel Response to pn-user-attributes
  PnCoreEventBusToUserAttributesQueue:
    Type: AWS::Events::Rule
    Properties: 
      Description: Route ExternalChannel Events to pn-user-attributes
      EventBusName: !Ref PnCoreEventBus
      EventPattern:
        detail-type: [ "ExternalChannelOutcomeEvent" ]
        details:
          clientId: [ "pn-user-attributes" ]
      Targets: 
        - Id: !Sub '${ProjectName}-CoreEventBus-ExtCh2UserAttributes'
          Arn: !GetAtt ExternalChannels2UserAttributesQueue.Outputs.QueueARN
          DeadLetterConfig: 
            Arn: !GetAtt EventBusDeadLetterQueue.Arn

  # Standard Queue for events Dead Letter Queue
  EventBusDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: !Ref EventBusDeadLetterQueueMaximumRetentionPeriod
      QueueName: !Sub '${ProjectName}-CoreEventBus-DLQ'

  # Dead Letter Queue policy 
  EventBusDeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref "EventBusDeadLetterQueue"
      PolicyDocument:
        Statement:
          - Sid: "SendEventsToDLQ"
            Effect: "Allow"
            Principal: 
              Service: 
                - "events.amazonaws.com"
            Action: 
              - "SQS:SendMessage"
            Resource:
              - !GetAtt "EventBusDeadLetterQueue.Arn"

  # Alarm for Dead letter queue has messages
  DLQHasMessagesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-CoreEventBus-DLQ-HasMessage'
      AlarmDescription: "CloudWatch alarm for when DLQ has 1 or more messages."
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions:
        - Name: "QueueName"
          Value: !Sub '${EventBusDeadLetterQueue.QueueName}'
      Statistic: "Sum"
      Period: 60  
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold" 
      EvaluationPeriods: 1       
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      InsufficientDataActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      OKActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'


Outputs:
  # Web API for browsers and B2B
  ApiDnsName:
    Value: !Ref ApiDnsName
    Description: 'The DNS name used for B2B rest API.'
  WebApiDnsName:
    Value: !Ref WebApiDnsName
    Description: 'The DNS name used for browser rest API.'
  IoApiDnsName:
    Value: !Ref IoApiDnsName
    Description: 'The DNS name used for browser rest API.'

  # SafeStorage to DeliveryPush
  SafeStorageToDeliveryPushQueueName:
    Value: !GetAtt SafeStorageToDeliveryPushQueue.Outputs.QueueName
    Description: SafeStorage-to-delivery-push queue name
  SafeStorageToDeliveryPushQueueURL:
    Value: !GetAtt SafeStorageToDeliveryPushQueue.Outputs.QueueURL
    Description: SafeStorage-to-delivery-push queue URL
  SafeStorageToDeliveryPushQueueARN:
    Value: !GetAtt SafeStorageToDeliveryPushQueue.Outputs.QueueARN
    Description: SafeStorage-to-delivery-push queue ARN

  # Delivery push inputs
  DeliveryPushInputsQueueName:
    Value: !GetAtt DeliveryPushInputsQueue.Outputs.QueueName
    Description: pn-delivery-push input queue name
  DeliveryPushInputsQueueURL:
    Value: !GetAtt DeliveryPushInputsQueue.Outputs.QueueURL
    Description: pn-delivery-push input queue URL
  DeliveryPushInputsQueueARN:
    Value: !GetAtt DeliveryPushInputsQueue.Outputs.QueueARN
    Description: pn-delivery-push input queue ARN

  # External channels inputs
  ExternalChannelsInputsQueueName:
    Value: !GetAtt ExternalChannelsInputsQueue.Outputs.QueueName
    Description: pn-external-channels input queue name
  ExternalChannelsInputsQueueURL:
    Value: !GetAtt ExternalChannelsInputsQueue.Outputs.QueueURL
    Description: pn-external-channels input queue URL
  ExternalChannelsInputsQueueARN:
    Value: !GetAtt ExternalChannelsInputsQueue.Outputs.QueueARN
    Description: pn-external-channels input queue ARN

  # External channels outputs
  ExternalChannelsOutputsQueueName:
    Value: !GetAtt ExternalChannelsOutputsQueue.Outputs.QueueName
    Description: pn-external-channels output queue name
  ExternalChannelsOutputsQueueURL:
    Value: !GetAtt ExternalChannelsOutputsQueue.Outputs.QueueURL
    Description: pn-external-channels output queue URL
  ExternalChannelsOutputsQueueARN:
    Value: !GetAtt ExternalChannelsOutputsQueue.Outputs.QueueARN
    Description: pn-external-channels output queue ARN

  # Timeline Change Data Capture
  TimelineCdcKinesisStreamName:
    Value: !GetAtt TimelineCdcKinesis.Outputs.KinesisStreamName
    Description: kinesis stream name for timeline dynamo table
  TimelineCdcKinesisStreamArn:
    Value: !GetAtt TimelineCdcKinesis.Outputs.KinesisStreamArn
    Description: kinesis stream Arn for timeline dynamo table
  TimelineCdcKinesisKeyArn:
    Value: !GetAtt TimelineCdcKinesis.Outputs.KinesisKeyArn
    Description: KMS key arn for timeline stream decryption

  # Notification Change Data Capture
  NotificationCdcKinesisStreamName:
    Value: !GetAtt NotificationCdcKinesis.Outputs.KinesisStreamName
    Description: kinesis stream name for notification dynamo table
  NotificationCdcKinesisStreamArn:
    Value: !GetAtt NotificationCdcKinesis.Outputs.KinesisStreamArn
    Description: kinesis stream Arn for notification dynamo table
  NotificationCdcKinesisKeyArn:
    Value: !GetAtt NotificationCdcKinesis.Outputs.KinesisKeyArn
    Description: KMS key arn for notification stream decryption

  # pass-thought parameters
  NetworkLoadBalancerLink:
    Value: !Ref NetworkLoadBalancerLink
  ApplicationLoadBalancerListenerArn:
    Value: !Ref ApplicationLoadBalancerListenerArn
  ApplicationLoadBalancerDomain:
    Value: !Ref ApplicationLoadBalancerDomain
  AlarmSNSTopicArn:
    Value: !Ref AlarmSNSTopicArn
  AlarmSNSTopicName:
    Value: !Ref AlarmSNSTopicName
  VpcId:
    Value: !Ref VpcId
  SubnetsIds:
    Value: !Ref SubnetsIds
  ECSClusterName:
    Value: !Ref ECSClusterName