AWSTemplateFormatVersion: 2010-09-09
Description: This templates enriches messages received from CloudWatch, CodePipeline and CodeBuild

Parameters:
  QueueName:
      Type: String
      Description:  Queue Name

  DelaySeconds:
    Description: 'The time in seconds that the delivery of all messages in the queue
      is delayed. You can specify an integer value of 0 to 900 (15 minutes).'
    Type: Number
    Default: '0'

  AlarmSNSTopicName:
    Description: The name of the existing Alarm SNS Topic for notifications.
    Type: String

  MessageRetentionPeriod:
    Description: 'The number of seconds that Amazon SQS retains a message. You can
      specify an integer value from 60 seconds (1 minute) to 1209600 seconds (14 days). '
    Type: Number
    Default: '600'

  MaxReceiveCount:
    Description: 'The number of times a message is delivered to the source queue before
      being moved to the dead-letter queue'
    Type: Number
    Default: '5'

  DeadLetterMessageRetentionPeriod:
    Description: 'The number of seconds that the DLQ retains a message. You can
      specify an integer value from 60 seconds (1 minute) to 1209600 seconds (14 days). '
    Type: Number
    Default: '1209600'
  
  SlackChannelId:
    Description: The Id of your slack channel.
    Type: String

  SlackTokenArn:
    Description: The ARN of the Slack Token Secret.
    Type: String
  
  VisibilityTimeout: 
    Description: The length of time during which a message will be unavailable after a message is delivered from the queue.
    Type: Number
    Default: '15'

  S3BucketName:
    Type: String
    Description: 'The S3 bucket where lambda is stored.'
  
Resources:
  MessageEnrichmentQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref MaxReceiveCount
      DelaySeconds: !Ref DelaySeconds
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      ReceiveMessageWaitTimeSeconds: 15
      VisibilityTimeout: !Ref VisibilityTimeout

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${QueueName}-DLQ"
      MessageRetentionPeriod: !Ref DeadLetterMessageRetentionPeriod

  MyQueueEventBridgePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MessageEnrichmentQueue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowMessages
            Effect: Allow
            Principal: 
              Service: 
              - sns.amazonaws.com 
            Action: SQS:SendMessage
            Resource: !GetAtt MessageEnrichmentQueue.Arn
          - Sid: AllowLambdaaccess
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - SQS:SendMessage
              - SQS:ReceiveMessage
              - SQS:DeleteMessage
              - SQS:GetQueueAttributes
            Resource: !GetAtt MessageEnrichmentQueue.Arn

  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: true
      BatchSize: 10
      EventSourceArn: !GetAtt MessageEnrichmentQueue.Arn
      FunctionName: !GetAtt MessageCustomizationLambda.Arn

  SNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: !GetAtt MessageEnrichmentQueue.Arn
      Protocol: sqs
      TopicArn: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
        
  MessageCustomizationLambda:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        S3Bucket: !Ref S3BucketName
        S3Key: MessageEnrich.zip
        #S3ObjectVersion: 1
      Description: AWS Lambda function to customize CloudWatch Alarm notification
      Environment:
         Variables:
          SlackChannelId: !Ref SlackChannelId
          SlackTokenArn: !Ref SlackTokenArn
      FunctionName: !Sub ${QueueName}-message-enrich-lambda
      Handler: index.lambda_handler
      Role: !GetAtt MessageCustomizationLambdaRole.Arn
      Runtime: python3.9
      Timeout: 15 #Queue wait time should be equal or greater then timeout

  # Lambda Execution role 
  MessageCustomizationLambdaRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      Description: AWS IAM Role for Lambda execution role
      Path: /
      RoleName: !Sub ${AWS::StackName}-Role

  # Lambda Policy  
  MessageCustomizationLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyDocument:
        Version: 2012-10-17
        Statement: 
          - Sid: InvokeLambda
            Effect: Allow
            Action: lambda:InvokeFunction
            Resource: !GetAtt MessageCustomizationLambda.Arn
          - Sid: AllowSQSAccess
            Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ChangeMessageVisibility
            Resource: !GetAtt MessageEnrichmentQueue.Arn
          - Sid: AllowAccessToLogs
            Effect: Allow
            Action: 
              - logs:DescribeLogStreams
              - logs:DescribeMetricFilters
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
          - Sid: AllowAccessToSecretsManager
            Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: !Ref SlackTokenArn
      PolicyName: !Sub ${QueueName}-Policy
      Roles: 
        - !Ref MessageCustomizationLambdaRole
