AWSTemplateFormatVersion: "2010-09-09"
Description: "Infra storage resources"

Parameters:
  
  ProjectName:
    Type: String
    Default: pn
    Description: Base name for pn project
  
  Version:
    Type: String

  BucketSuffix:
    Type: String
    Description: Suffix to the log bucket name
  
  TemplateBucketBaseUrl:
    Type: String
    Description: infra fragment source
  
  SafeStorageAccountId:
    Type: String
    Default: '-'
    Description: Safestorage Account ID

  CdcStreamRetentionHours:
    Type: Number
    Description: 'Change Data Capture Kinesis Data Stream retention period in hours'

  CdcStreamShardCount:
    Type: Number
    Default: 0
    Description: 'Number of shards in the stream'

  CdcStreamMode:
    Description: Stream Mode.
    Default: ON_DEMAND
    Type: String
    AllowedValues: [ON_DEMAND, PROVISIONED]

  LogsStreamRetentionHours:
    Type: Number
    Description: 'Cloudwatch Logs Kinesis Data Stream retention period in hours'

  LogsStreamShardCount:
    Type: Number
    Default: 0
    Description: 'Number of shards in the stream'

  LogsStreamMode:
    Description: Stream Mode.
    Default: ON_DEMAND
    Type: String
    AllowedValues: [ON_DEMAND, PROVISIONED]
  
  PnCoreAwsAccountId:
    Type: String
    Default: '-'
    Description: AWS AccountId of pn-core account in same environment
  
  SafeStorageFileAccessLogsBucketPathPrefix:
    Type: String
    Default: safeStorageObjectPutAndGetTracing

  AlarmSNSTopicArn:
    Type: String

  AlarmSNSTopicName:
    Type: String

  LogRetention:
    Type: Number
    Default: 14
    Description: 'Log retention in days'

  BucketLogRetentionDays:
    Type: Number
    Default: 1095 # 3 years
    Description: Number of days to retain logs in the bucket

  BucketLogPrefix:
    Type: String
    Default: 'logsTos3/'
    Description: Prefix for the logs in the bucket

  BucketCdcRetentionDays:
    Type: Number
    Default: 1095 # 3 years
    Description: Number of days to retain cdc in the bucket

  BucketCdcPrefix:
    Type: String
    Default: 'cdcTos3/'
    Description: Prefix for the cdc in the bucket

Conditions:
  MakeBucketCondition: !Not [ !Equals [ !Ref BucketSuffix, '' ]]
  
  HasStorageStorageAccountId: !Not [ !Equals [ !Ref SafeStorageAccountId, '-' ]]

  ActivateSafeStorageCondition: !And [ !Condition MakeBucketCondition, !Condition HasStorageStorageAccountId]

  CdcOnDemandDisabled: !Not [!Equals [!Ref CdcStreamMode, ON_DEMAND]]
  LogsOnDemandDisabled: !Not [!Equals [!Ref LogsStreamMode, ON_DEMAND]]

  HasPnCoreAwsAccountId: !Not [ !Equals [ !Ref PnCoreAwsAccountId, '-' ] ]

Resources:
  
  ### - S3 Bucket for logs storages
  ###########################################
  LogsBucket:
    Condition: MakeBucketCondition
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-logs-bucket-${AWS::Region}-${AWS::AccountId}-${BucketSuffix}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref LogsBucketKmsKey              
              SSEAlgorithm: 'aws:kms'
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteLogs
            Status: Enabled
            Prefix: !Ref BucketLogPrefix
            ExpirationInDays: !Ref BucketLogRetentionDays   
          - Id: DeleteNoncurrentLogs
            Status: Enabled
            Prefix: !Ref BucketLogPrefix
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
          - Id: DeleteCdc
            Status: Enabled
            Prefix: !Ref BucketCdcPrefix
            ExpirationInDays: !Ref BucketCdcRetentionDays   
          - Id: DeleteNoncurrentCdc
            Status: Enabled
            Prefix: !Ref BucketCdcPrefix
            NoncurrentVersionExpiration:
              NoncurrentDays: 1          
      NotificationConfiguration:
        QueueConfigurations:
          - Event: 's3:ObjectCreated:*'
            Filter: 
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref SafeStorageFileAccessLogsBucketPathPrefix
            Queue: !GetAtt NewSafeStorageCloudTrailFileQueue.Outputs.QueueARN
          - Event: 's3:ObjectCreated:*'
            Filter: 
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'diagnosticTrail'
            Queue: !GetAtt DiagnosticCloudTrailFileQueue.Outputs.QueueARN
      
  # - Log storage cryptography key 
  LogsBucketKmsKey:
    Condition: MakeBucketCondition
    DependsOn:
      - NewSafeStorageCloudTrailFileQueueResourcePolicy
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: Used by Assumed Roles to Encrypt/Decrypt raw data
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Ref AWS::StackName
        Statement:
          - Sid: Allow data account to do everything
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
              - kms:*Tag*
              - kms:*tag*
            Resource: "*"
          - Sid: Allow target accounts to use key for encrypt/decrypt
            Effect: Allow
            Principal:
              AWS:
                Fn::If:
                  - HasPnCoreAwsAccountId
                  - - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
                    - !Sub arn:${AWS::Partition}:iam::${PnCoreAwsAccountId}:root
                  - - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
          - Fn::If:
            - ActivateSafeStorageCondition
            - Sid: Allow safe storage kms usage
              Effect: Allow
              Action:
                - kms:Encrypt
                - kms:Decrypt
                - kms:GenerateDataKey*
              Principal:
                Service: "cloudtrail.amazonaws.com"
              Resource: "*"
              Condition:
                ArnLike: 
                  aws:SourceArn: !Sub "arn:${AWS::Partition}:cloudtrail:${AWS::Region}:${SafeStorageAccountId}:trail/*"
            - !Ref AWS::NoValue


  NewSafeStorageCloudTrailFileQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain      
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-new-safestorage-cloudtrail-file'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName    

  # Export new safestorage cloudtrail file events
  NewSafeStorageCloudTrailFileQueueResourcePolicy:
    Type: AWS::SQS::QueuePolicy
    Condition: MakeBucketCondition
    Properties: 
      Queues: 
        - !GetAtt NewSafeStorageCloudTrailFileQueue.Outputs.QueueURL
      PolicyDocument:
        Statement: 
          - Fn::If:
            - HasPnCoreAwsAccountId
            - Sid: pnCoreAccountGet
              Effect: "Allow"
              Principal:  
                AWS:
                  - !Sub arn:${AWS::Partition}:iam::${PnCoreAwsAccountId}:root
              Action: 
                - "sqs:ReceiveMessage"
                - "sqs:DeleteMessage"
                - "sqs:GetQueueAttributes"
                - "sqs:ChangeMessageVisibility"
                - "sqs:GetQueueUrl"
              Resource: !GetAtt NewSafeStorageCloudTrailFileQueue.Outputs.QueueARN
            - !Ref "AWS::NoValue"
          - Sid: s3ServicePut
            Effect: "Allow"
            Principal:  
              Service: 
                - "s3.amazonaws.com"
            Action: 
              - "sqs:SendMessage"
              - "sqs:GetQueueAttributes"
              - "sqs:ChangeMessageVisibility"
              - "sqs:GetQueueUrl"
            Resource: !GetAtt NewSafeStorageCloudTrailFileQueue.Outputs.QueueARN
            Condition:
              ArnLike:
                "aws:SourceArn": !Sub "arn:${AWS::Partition}:s3:*:*:${ProjectName}-logs-bucket-${AWS::Region}-${AWS::AccountId}-${BucketSuffix}"
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId

  RuntimeEnvironmentVariablesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-runtime-environment-variables-${AWS::Region}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ## KINESIS SOURCE STREAM FOR Change Data Capture

  ### AWS KMS / Server-side encryption for Kinesis Stream 
  CdcKinesisServerSideEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  ### Kinesis Data Stream 
  CdcKinesisStream:
    Type: AWS::Kinesis::Stream
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub '${ProjectName}-confidential-cdc-source-stream'
      RetentionPeriodHours: !Ref CdcStreamRetentionHours
      ShardCount: !If [CdcOnDemandDisabled, !Ref CdcStreamShardCount, !Ref "AWS::NoValue"]
      StreamEncryption:
        EncryptionType: KMS
        KeyId:
          Fn::GetAtt:
            - CdcKinesisServerSideEncryptionKey
            - Arn
      StreamModeDetails:
        StreamMode: !Ref CdcStreamMode   

  ## KINESIS SOURCE STREAM FOR Logs
  LogsKinesisServerSideEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  ### Kinesis Data Stream 
  LogsKinesisStream:
    Type: AWS::Kinesis::Stream
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub '${ProjectName}-confidential-logs-source-stream'
      RetentionPeriodHours: !Ref LogsStreamRetentionHours
      ShardCount: !If [LogsOnDemandDisabled, !Ref LogsStreamShardCount, !Ref "AWS::NoValue"]
      StreamEncryption:
        EncryptionType: KMS
        KeyId:
          Fn::GetAtt:
            - LogsKinesisServerSideEncryptionKey
            - Arn
      StreamModeDetails:
        StreamMode: !Ref LogsStreamMode   
        
  # Diagnostic trail resources
  DiagnosticLambdaLoggerName:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-diagnostic-logger'
        LogGroupPrefix: '/aws/lambda'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !GetAtt LogsKinesisStream.Arn

  DiagnosticCloudTrailFileQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain      
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-diagnostic-cloudtrail-file'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName    

  # Export new safestorage cloudtrail file events
  DiagnosticCloudTrailFileQueueResourcePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !GetAtt DiagnosticCloudTrailFileQueue.Outputs.QueueURL
      PolicyDocument:
        Statement: 
          - Sid: pnConfinfoAccountGet
            Effect: "Allow"
            Principal:  
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: 
              - "sqs:ReceiveMessage"
              - "sqs:DeleteMessage"
              - "sqs:GetQueueAttributes"
              - "sqs:ChangeMessageVisibility"
              - "sqs:GetQueueUrl"
            Resource: !GetAtt DiagnosticCloudTrailFileQueue.Outputs.QueueARN
          - Sid: s3ServicePut
            Effect: "Allow"
            Principal:  
              Service: 
                - "s3.amazonaws.com"
            Action: 
              - "sqs:SendMessage"
              - "sqs:GetQueueAttributes"
              - "sqs:ChangeMessageVisibility"
              - "sqs:GetQueueUrl"
            Resource: !GetAtt DiagnosticCloudTrailFileQueue.Outputs.QueueARN
            Condition:
              ArnLike:
                "aws:SourceArn": !Sub "arn:${AWS::Partition}:s3:*:*:${ProjectName}-logs-bucket-${AWS::Region}-${AWS::AccountId}-${BucketSuffix}"
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId

Outputs:
  LogsBucketKmsKeyArn:
    Value: 
      Fn::If:
        - MakeBucketCondition
        - !GetAtt LogsBucketKmsKey.Arn
        - ''
  
  LogsBucketName:
    Value: 
      Fn::If:
        - MakeBucketCondition
        - !Ref LogsBucket
        - ''

  CdcKinesisStreamName:
    Value: !Ref CdcKinesisStream
    Description: 'Kinesis source stream name'
  
  CdcKinesisStreamArn:
    Value: !GetAtt CdcKinesisStream.Arn
    Description: 'Kinesis source stream name ARN'

  CdcKinesisStreamKeyArn:
    Value: !GetAtt CdcKinesisServerSideEncryptionKey.Arn
    Description: 'Arn of the KMS key used to encrypt the Kinesis source stream'

  LogsKinesisStreamName:
    Value: !Ref LogsKinesisStream
    Description: 'Kinesis source stream name'
  
  LogsKinesisStreamArn:
    Value: !GetAtt LogsKinesisStream.Arn
    Description: 'Kinesis source stream name ARN'

  LogsKinesisStreamKeyArn:
    Value: !GetAtt LogsKinesisServerSideEncryptionKey.Arn
    Description: 'Arn of the KMS key used to encrypt the Kinesis source stream'

  BucketSuffix: # used to generate kms alias
    Value: !Ref BucketSuffix
  
  # new safestorage cloudtrail file event queue
  NewSafeStorageCloudTrailFileQueueName:
    Value: !GetAtt NewSafeStorageCloudTrailFileQueue.Outputs.QueueName
    Description: new safestorage cloudtrail file event queue name
  NewSafeStorageCloudTrailFileQueueURL:
    Value: !GetAtt NewSafeStorageCloudTrailFileQueue.Outputs.QueueURL
    Description: new safestorage cloudtrail file event queue URL
  NewSafeStorageCloudTrailFileQueueARN:
    Value: !GetAtt NewSafeStorageCloudTrailFileQueue.Outputs.QueueARN
    Description: new safestorage cloudtrail file event queue ARN
  NewSafeStorageCloudTrailFileQueueAlarmARN:
    Value: !GetAtt NewSafeStorageCloudTrailFileQueue.Outputs.SqsDLQAlarmArn
    Description: new safestorage cloudtrail file event queue alarm ARN
  NewSafeStorageCloudTrailFileQueueAgeAlarmARN:
    Value: !GetAtt NewSafeStorageCloudTrailFileQueue.Outputs.SqsAgeAlarmArn
    Description: new safestorage cloudtrail file event queue ARN
  

  # Pass through parameters
  AlarmSNSTopicArn:
    Value: !Ref AlarmSNSTopicArn

  AlarmSNSTopicName:
    Value: !Ref AlarmSNSTopicName
  
  SafeStorageAccountId:
    Value: !Ref SafeStorageAccountId
  
  PnCoreAwsAccountId:
    Value: !Ref PnCoreAwsAccountId
  
  SafeStorageFileAccessLogsBucketName:
    Value: 
      Fn::If:
        - MakeBucketCondition
        - !Ref LogsBucket
        - ''
    
  SafeStorageFileAccessLogsBucketPathPrefix:
    Value: !Ref SafeStorageFileAccessLogsBucketPathPrefix

  Version:
    Value: !Ref Version

  LogRetention:
    Value: !Ref LogRetention