AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create Roles in Account Hotfix

Parameters:
  ExecutionRoleLambdaUpdateTrustPolicies:
    Type: String
    Description: "Enter the ARN of the execution role of the Lambda (CICD Account) that updates the trust policies"

  RoleReadOnlyAccessARN:
    Type: String
    Description: "Enter the ARN of the ReadOnlyAccess Role of this account"

  RoleAdministratorAccessARN:
    Type: String
    Description: "Enter the ARN of the AdminstratorAccess role of this account"


Resources:
  # Role that the Lambda UpdateTrustPolicy (in CICD Account) will assume to update the Trust Policies in this account
  RoleUpdateTrustPolicy:
    Type: AWS::IAM::Role
    Properties:
      RoleName: UpdateTrustPolicies-HOTFIX
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              # ARN of the Lambda Function's Role in Account CICD
              AWS: !Ref ExecutionRoleLambdaUpdateTrustPolicies
            Action: 
              - "sts:AssumeRole"
  
  PolicyUpdateTrustPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: UpdateTrustPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "iam:UpdateAssumeRolePolicy"
              - "iam:GetRole" 
            Resource:
              - !Ref RoleReadOnlyAccessARN
              - !Ref RoleAdministratorAccessARN
      Roles:
        - !Ref RoleUpdateTrustPolicy 

Outputs:
  RoleUpdateTrustPolicy:
    Description: "ARN of the UpdateTrustPolicy role"
    Value: !GetAtt RoleUpdateTrustPolicy.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ARN-RoleUpdateTrustPolicy"