AWSTemplateFormatVersion: '2010-09-09'
Description: 'Expose a microservice API using API-GW. This template can expose API for B2B or WEB usage'

Resources:
  IOBackEndUsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    Properties:
      UsagePlanName: APP_IO_BE
      Description: Usage Plan for app IO back end
      # Quota removed
      Throttle:
        BurstLimit: 2000
        RateLimit: 1000