AWSTemplateFormatVersion: 2010-09-09
Description: Creates CloudWatch Alarms for errors grouped by monitoring groups from OpenAPI specification

Parameters:
  ApiGatewayId:
    Type: String
    Description: ID of the API Gateway

  PublicRestApiStage:
    Type: String
    Description: ID of the API Gateway

  OpenApiBucketName:
    Type: String
    Description: Bucket name where the OpenAPI files are located

  OpenApiBucketKey:
    Type: String
    Description: Bucket key of the OpenAPI file in the s3 bucket

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of the SNS Topic for alarms

  MicroServiceUniqueName:
    Type: String
    Description: Unique name of the microservice

  IntendedUsage:
    Type: String
    AllowedValues:
      - B2B
      - WEB
      - IO
      - BACKOFFICE
      - PNPG
      - CN_BE
      - RADD
      - B2BPG
      - PUBLIC
    Description: B2B, WEB, BACKOFFICE, RADD, PNPG or IO usage. Used from other back-end system or used from a browser

  AlarmOn4xx:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: "Enable alarms for 4XX errors"

  StandardApiErrorDataPointsToAlarm:
    Type: Number
    Default: 1
    Description: "Number of datapoints to trigger standard alarm"

  StandardApiErrorEvaluationPeriods:
    Type: Number
    Default: 5
    Description: "Evaluation periods for standard alarm"

  StandardApiErrorThreshold:
    Type: Number
    Default: 1
    Description: "Threshold for standard API errors"

  StandardApiErrorPeriod:
    Type: Number
    Default: 60
    Description: "Period for standard API errors in seconds"

  StandardApiErrorStat:
    Type: String
    Default: "Sum"
    Description: "Statistic for standard API errors"

  StandardApiErrorComparisonOperator:
    Type: String
    Default: "GreaterThanThreshold"
    Description: "Comparison operator for standard API errors"

  StandardApiErrorMissingData:
    Type: String
    Default: "notBreaching"
    Description: "Missing data behavior for standard API errors"

  OncallApiErrorDataPointsToAlarm:
    Type: Number
    Default: 20
    Description: "Number of datapoints to trigger oncall alarm"
    
  OncallApiErrorEvaluationPeriods:
    Type: Number
    Default: 60
    Description: "Evaluation periods for oncall alarm"

  OncallApiError4xxDataPointsToAlarm:
    Type: Number
    Default: 30
    Description: "Number of datapoints to trigger oncall 4xx alarm"

  OncallApiError4xxEvaluationPeriods:
    Type: Number
    Default: 90
    Description: "Evaluation periods for oncall 4xx alarm"

  OncallApiErrorCountThreshold:
    Type: Number
    Default: 10
    Description: "Threshold for oncall API error count"

  OncallApiError5xxThreshold:
    Type: Number
    Default: 0.1
    Description: "Threshold for oncall 5xx errors"

  OncallApiError4xxThreshold:
    Type: Number
    Default: 0.9
    Description: "Threshold for oncall 4xx errors"

  OncallApiErrorPeriod:
    Type: Number
    Default: 60
    Description: "Period for oncall API errors in seconds"

  OncallApiErrorStat:
    Type: String
    Default: "Average"
    Description: "Statistic for oncall API errors"

  OncallApiErrorCountStat:
    Type: String
    Default: "Sum"
    Description: "Statistic for oncall API error count"

  OncallApiErrorComparisonOperator:
    Type: String
    Default: "GreaterThanThreshold"
    Description: "Comparison operator for oncall API errors"

  OncallApiErrorMissingData:
    Type: String
    Default: "notBreaching"
    Description: "Missing data behavior for oncall API errors"

  OncallApiErrorThreshold:
    Type: Number
    Default: 0
    Description: "General threshold for oncall API errors"

Resources:
  'Fn::Transform':
    Name: 'ApiAlarmsSegmentationMacro'
    Parameters:
      OpenApiBucketName: !Ref OpenApiBucketName
      OpenApiBucketKey: !Ref OpenApiBucketKey
      ApiGatewayId: !Ref ApiGatewayId
      PublicRestApiStage: !Ref PublicRestApiStage
      AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
      MicroServiceUniqueName: !Ref MicroServiceUniqueName
      IntendedUsage: !Ref IntendedUsage
      AlarmOn4xx: !Ref AlarmOn4xx
      StandardApiErrorDataPointsToAlarm: !Ref StandardApiErrorDataPointsToAlarm
      StandardApiErrorEvaluationPeriods: !Ref StandardApiErrorEvaluationPeriods
      StandardApiErrorThreshold: !Ref StandardApiErrorThreshold
      StandardApiErrorPeriod: !Ref StandardApiErrorPeriod
      StandardApiErrorStat: !Ref StandardApiErrorStat
      StandardApiErrorComparisonOperator: !Ref StandardApiErrorComparisonOperator
      StandardApiErrorMissingData: !Ref StandardApiErrorMissingData
      OncallApiErrorDataPointsToAlarm: !Ref OncallApiErrorDataPointsToAlarm
      OncallApiErrorEvaluationPeriods: !Ref OncallApiErrorEvaluationPeriods
      OncallApiError4xxDataPointsToAlarm: !Ref OncallApiError4xxDataPointsToAlarm
      OncallApiError4xxEvaluationPeriods: !Ref OncallApiError4xxEvaluationPeriods
      OncallApiErrorCountThreshold: !Ref OncallApiErrorCountThreshold
      OncallApiError5xxThreshold: !Ref OncallApiError5xxThreshold
      OncallApiError4xxThreshold: !Ref OncallApiError4xxThreshold
      OncallApiErrorPeriod: !Ref OncallApiErrorPeriod
      OncallApiErrorStat: !Ref OncallApiErrorStat
      OncallApiErrorCountStat: !Ref OncallApiErrorCountStat
      OncallApiErrorComparisonOperator: !Ref OncallApiErrorComparisonOperator
      OncallApiErrorMissingData: !Ref OncallApiErrorMissingData
      OncallApiErrorThreshold: !Ref OncallApiErrorThreshold

Outputs:
  # Invocation to generate Outputs
  'Fn::Transform':
    Name: ApiAlarmsSegmentationMacro
    Parameters:
      Action: 'Outputs' #Create only outputs
      OpenApiBucketName: !Ref OpenApiBucketName
      OpenApiBucketKey: !Ref OpenApiBucketKey
      ApiGatewayId: !Ref ApiGatewayId
      PublicRestApiStage: !Ref PublicRestApiStage
      MicroServiceUniqueName: !Ref MicroServiceUniqueName
      IntendedUsage: !Ref IntendedUsage
      AlarmOn4xx: !Ref AlarmOn4xx
      StandardApiErrorDataPointsToAlarm: !Ref StandardApiErrorDataPointsToAlarm
      StandardApiErrorEvaluationPeriods: !Ref StandardApiErrorEvaluationPeriods
      StandardApiErrorThreshold: !Ref StandardApiErrorThreshold
      StandardApiErrorPeriod: !Ref StandardApiErrorPeriod
      StandardApiErrorStat: !Ref StandardApiErrorStat
      StandardApiErrorComparisonOperator: !Ref StandardApiErrorComparisonOperator
      StandardApiErrorMissingData: !Ref StandardApiErrorMissingData
      OncallApiErrorDataPointsToAlarm: !Ref OncallApiErrorDataPointsToAlarm
      OncallApiErrorEvaluationPeriods: !Ref OncallApiErrorEvaluationPeriods
      OncallApiError4xxDataPointsToAlarm: !Ref OncallApiError4xxDataPointsToAlarm
      OncallApiError4xxEvaluationPeriods: !Ref OncallApiError4xxEvaluationPeriods
      OncallApiErrorCountThreshold: !Ref OncallApiErrorCountThreshold
      OncallApiError5xxThreshold: !Ref OncallApiError5xxThreshold
      OncallApiError4xxThreshold: !Ref OncallApiError4xxThreshold
      OncallApiErrorPeriod: !Ref OncallApiErrorPeriod
      OncallApiErrorStat: !Ref OncallApiErrorStat
      OncallApiErrorCountStat: !Ref OncallApiErrorCountStat
      OncallApiErrorComparisonOperator: !Ref OncallApiErrorComparisonOperator
      OncallApiErrorMissingData: !Ref OncallApiErrorMissingData
      OncallApiErrorThreshold: !Ref OncallApiErrorThreshold
