AWSTemplateFormatVersion: '2010-09-09'
Description: Fragment for Glue Table and Crawler for CDC files analysis
Parameters:
  GlueDatabaseName:
    Description: Name of the Glue Database
    Type: String
  ProjectName:
    Type: String
    Default: pn
    Description: Base name for pn project    
  LogsBucketName:
    Type: String
    Description: Logs bucket name
  TableName:
    Description: Name of the Glue table
    Type: String
  TableS3Prefix:
    Description: Name of the Glue table
    Type: String
  DynamoDBKeysStructure:
    Description: Structure of the dynamodb column
    Type: String
  DynamoDBNewImageStructure:
    Description: Structure of the dynamodb column
    Type: String
  CdcRecordFilter:
    Description: Filter technical dynamo table record
    Type: String
    Default: ""
  GenerateCdcView:
    Description: Set to false to disable view generation
    Type: String
    Default: "true"
  GlueCrawlerSchedule:
    Type: String
    Default: ''
    Description: Cron expression for the Glue Crawler schedule.
  GlueServiceRoleArn:
    Type: String
    Description: Service role for the Glue Crawler.

Conditions:
  IsGlueCrawlerScheduled: !Not
    - !Equals
      - !Ref GlueCrawlerSchedule
      - ''
  HasCdcView: !Equals [ "true", !Ref GenerateCdcView ]

Resources:
  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabaseName
      TableInput:
        Name: !Ref TableName
        TableType: EXTERNAL_TABLE
        PartitionKeys:
          - Name: p_year
            Type: string
            Comment: Kinesis stream partition year
          - Name: p_month
            Type: string
            Comment: Kinesis stream partition month
          - Name: p_day
            Type: string
            Comment: Kinesis stream partition day
          - Name: p_hour
            Type: string
            Comment: Kinesis stream partition hour
        StorageDescriptor:
          Columns:
            - Name: awsRegion
              Type: string
            - Name: eventID
              Type: string
            - Name: eventName
              Type: string
            - Name: userIdentity
              Type: string
            - Name: recordFormat
              Type: string
            - Name: tableName
              Type: string
            - Name: dynamodb
              Type: !Join
                - ''
                - !Split
                  - ' '
                  - !Join
                    - ''
                    - !Split
                      - "\n"
                      - !Sub "struct<ApproximateCreationDateTime:bigint,SizeBytes:bigint,Keys:${DynamoDBKeysStructure},NewImage:${DynamoDBNewImageStructure}>"
          Location: !Sub s3://${LogsBucketName}/cdcTos3/${TableS3Prefix}/
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Compressed: false
          SerdeInfo:
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
          StoredAsSubDirectories: false
  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      DatabaseName: !Ref GlueDatabaseName
      Name: !Sub ${TableName}_crawler
      Role: !Ref GlueServiceRoleArn
      Targets:
        CatalogTargets:
          - DatabaseName: !Ref GlueDatabaseName
            Tables:
              - !Ref TableName
      SchemaChangePolicy:
        UpdateBehavior: LOG
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Schedule: !If
        - IsGlueCrawlerScheduled
        - ScheduleExpression: !Ref GlueCrawlerSchedule
        - !Ref AWS::NoValue
  
  CdcGlueView:
    Condition: HasCdcView
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabaseName
      TableInput:
        Name: !Sub '${TableName}_view'
        TableType: VIRTUAL_VIEW
        Parameters:
          presto_view: 'true'
          comment: !Sub "Presto View for ${TableName} cdc"
        StorageDescriptor:
          Columns:
            'Fn::Transform':
              Name: 'GenerateCdcViewMacro'
              Parameters:
                DatabaseName: !Ref GlueDatabaseName
                CatalogName : 'awsdatacatalog'
                CdcTableName: !Ref TableName
                CdcViewName: !Sub '${TableName}_view'
                CdcKeysType: !Ref DynamoDBKeysStructure
                CdcNewImageType: !Ref DynamoDBNewImageStructure
                CdcRecordFilter: !Ref CdcRecordFilter
                OutputType: 'StorageDescriptor-Columns'
                Enabled: # Enable or disable heavy transformation computation if not needed
                  Fn::If:
                    - HasCdcView
                    - "true"
                    - "false"
          Location: ""
          SerdeInfo: {}
        ViewExpandedText: "/* Presto View */"
        ViewOriginalText:
          'Fn::Transform':
            Name: 'GenerateCdcViewMacro'
            Parameters:
              DatabaseName: !Ref GlueDatabaseName
              CatalogName : 'awsdatacatalog'
              CdcTableName: !Ref CdcTableName
              CdcViewName: !Sub '${TableName}_view'
              CdcKeysType: !Ref DynamoDBKeysStructure
              CdcNewImageType: !Ref DynamoDBNewImageStructure
              CdcRecordFilter: !Ref CdcRecordFilter
              OutputType: 'ViewOriginalText'
              Enabled: # Enable or disable heavy transformation computation if not needed
                Fn::If:
                  - HasCdcView
                  - "true"
                  - "false"
  
Outputs:
  GlueTableName:
    Description: Name of the created Glue Table
    Value: !Ref TableName
  GlueCrawlerName:
    Description: Name of the created Glue Crawler
    Value: !Ref GlueCrawler
  GlueViewName:
    Description: Name of the created Glue View
    Value: 
      Fn::If:
        - HasCdcView
        - !Sub '${TableName}_view'
        - "-"

