AWSTemplateFormatVersion: "2010-09-09"
Description: "Metric Filter for CloudWatch Logs with support for exclusion patterns via Metric Math."

Parameters:
  AlarmSNSTopicArn:
    Type: String
    Description: "SNS Topic ARN to send alarm notifications"

  MetricName:
    Type: String
    Description: "Base name of the metric to create (e.g., ANPR-Errors)"

  MetricNamespace:
    Type: String
    Description: "Namespace of the metric to create"

  LogGroupName:
    Type: String
    Description: "Log group name to create metric filter for"

  FilterPattern:
    Type: String
    Description: "Pattern to match the logs you want to count"

  ExcludeFilterPattern:
    Type: String
    Description: "Optional. Pattern to match logs you want to EXCLUDE from the count. Leave empty if not needed."
    Default: ""

  Period: 
    Type: Number
    Default: 60
    Description: "Period in seconds for the alarm"

  Threshold:
    Type: Number
    Default: 1
    Description: "Threshold for the alarm"

  EvaluationPeriods:
    Type: Number
    Default: 1
    Description: "Number of periods over which data is compared to the specified threshold"

  DatapointsToAlarm:
    Type: Number
    Default: 1
    Description: "Number of data points that must be breaching to trigger the alarm"

  ComparisonOperator:
    Type: String
    Description: "The arithmetic operation to use when comparing the specified statistic and threshold"

  Statistic:
    Type: String
    Description: "The statistic for the metric associated with the alarm"
  
  # On-call Parameters...
  OncallPeriod: 
    Type: Number
    Default: 60
    Description: "Period in seconds for the on-call alarm"

  OncallThreshold:
    Type: Number
    Default: 1
    Description: "Threshold for the on-call alarm"

  OncallEvaluationPeriods:
    Type: Number
    Default: 1
    Description: "Number of periods over which data is compared to the specified threshold"

  OncallDatapointsToAlarm:
    Type: Number
    Default: 1
    Description: "Number of data points that must be breaching to trigger the on-call alarm"

  OncallComparisonOperator:
    Type: String
    Default: ""
    Description: "The arithmetic operation to use when comparing the specified statistic and threshold"

  OncallStatistic:
    Type: String
    Default: ""
    Description: "The statistic for the metric associated with the alarm"

  HasOncall:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Conditions:
  HasOncallCondition: !Equals [ !Ref HasOncall, 'true' ]
  HasExcludeFilterPatternCondition: !Not [!Equals [!Ref ExcludeFilterPattern, ""]]

Resources:
  # Metric filter for logs to INCLUDE in the count
  IncludeMetricFilter: 
    Type: AWS::Logs::MetricFilter
    Properties: 
      LogGroupName: !Ref LogGroupName
      FilterPattern: !Ref FilterPattern
      MetricTransformations: 
        - MetricValue: 1
          MetricNamespace: !Ref MetricNamespace
          MetricName: !Ref MetricName

  # CONDITIONAL metric filter for logs to EXCLUDE from the count
  ExcludeMetricFilter:
    Type: AWS::Logs::MetricFilter
    Condition: HasExcludeFilterPatternCondition
    Properties:
      LogGroupName: !Ref LogGroupName
      FilterPattern: !Ref ExcludeFilterPattern
      MetricTransformations:
        - MetricValue: 1
          MetricNamespace: !Ref MetricNamespace
          MetricName: !Sub "${MetricName}-Exclude" # e.g., ANPR-Errors-Exclude

  # Standard Alarm using METRIC MATH
  CustomErrorLogsMetricAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${MetricName}-Alarm"
      AlarmDescription: !Sub "CloudWatch alarm for expression: (Total ${MetricName}) - (Excluded). Triggers if > ${Threshold}."
      TreatMissingData: notBreaching
      AlarmActions: 
        - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: !Ref DatapointsToAlarm
      ComparisonOperator: !Ref ComparisonOperator
      EvaluationPeriods: !Ref EvaluationPeriods
      Threshold: !Ref Threshold
      Metrics:
        - Id: "m1"
          MetricStat:
            Metric:
              Namespace: !Ref MetricNamespace
              MetricName: !Ref MetricName
            Period: !Ref Period
            Stat: !Ref Statistic
          ReturnData: false
        - Id: "m2"
          MetricStat:
            Metric:
              Namespace: !Ref MetricNamespace
              MetricName: !Sub "${MetricName}-Exclude"
            Period: !Ref Period
            Stat: !Ref Statistic
          ReturnData: false
        - Id: "e1"
          Expression: "m1 - FILL(m2, 0)"
          Label: !Ref MetricName
          ReturnData: true

  # On-Call Alarm using METRIC MATH
  OncallCustomErrorLogsMetricAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasOncallCondition
    Properties:
      AlarmName: !Sub "oncall-${MetricName}-Alarm"
      AlarmDescription: !Sub "CloudWatch on-call alarm for expression: (Total ${MetricName}) - (Excluded). Triggers if > ${OncallThreshold}."
      TreatMissingData: notBreaching
      AlarmActions: 
        - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: !Ref OncallDatapointsToAlarm
      ComparisonOperator: !Ref OncallComparisonOperator
      EvaluationPeriods: !Ref OncallEvaluationPeriods
      Threshold: !Ref OncallThreshold
      Metrics:
        - Id: "m1"
          MetricStat:
            Metric:
              Namespace: !Ref MetricNamespace
              MetricName: !Ref MetricName
            Period: !Ref OncallPeriod
            Stat: !Ref OncallStatistic
          ReturnData: false
        - Id: "m2"
          MetricStat:
            Metric:
              Namespace: !Ref MetricNamespace
              MetricName: !Sub "${MetricName}-Exclude"
            Period: !Ref OncallPeriod
            Stat: !Ref OncallStatistic
          ReturnData: false
        - Id: "e1"
          Expression: "m1 - FILL(m2, 0)"
          Label: !Ref MetricName
          ReturnData: true