AWSTemplateFormatVersion: "2010-09-09"
Description: "Metric Filter for CloudWatch Logs"

Parameters:
  AlarmSNSTopicArn:
    Type: String
    Description: "SNS Topic ARN to send alarm notifications"

  MetricName:
    Type: String
    Description: "Name of the metric to create"

  MetricNamespace:
    Type: String
    Description: "Namespace of the metric to create"

  LogGroupName:
    Type: String
    Description: "Log group name to create metric filter for"

  FilterPattern:
    Type: String
    Description: "Pattern to filter logs"

  Period: 
    Type: Number
    Default: 60
    Description: "Period in seconds for the metric filter"

  Threshold:
    Type: Number
    Default: 1
    Description: "Threshold for the alarm"

  EvaluationPeriods:
    Type: Number
    Default: 1
    Description: "Number of periods over which data is compared to the specified threshold"

  DatapointsToAlarm:
    Type: Number
    Default: 1
    Description: "Number of data points that must be breaching to trigger the alarm"
Resources:
  # CloudWatch metric to filer ERROR - FATAL lines, in Log group
  CustomErrorLogsMetricFilter: 
    Type: AWS::Logs::MetricFilter
    Properties: 
      LogGroupName: !Ref LogGroupName
      FilterPattern: !Ref FilterPattern
      MetricTransformations: 
        - MetricValue: 1
          MetricNamespace: !Ref MetricNamespace
          MetricName: !Ref MetricName

  
  
  # Create alarm
  CustomErrorLogsMetricAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: CustomErrorLogsMetricFilter
    Properties:
      AlarmName: !Sub "${MetricName}-Alarm"
      AlarmDescription: !Sub "CloudWatch alarm on metric ${MetricName}."
      TreatMissingData: notBreaching
      AlarmActions: 
        - !Ref AlarmSNSTopicArn
      #InsufficientDataActions:
      #  - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: !Ref DatapointsToAlarm
      MetricName: !Ref MetricName
      Namespace: !Ref MetricNamespace
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: !Ref EvaluationPeriods
      Period: !Ref Period
      Statistic: Sum
      Threshold: !Ref Threshold