AWSTemplateFormatVersion: '2010-09-09'
Description: Add an ECS Service to an exsisting ECS cluster

Transform:
  - AddLambdaContextTransform

Parameters:

  # Logical parameters
  FunctionName:
    Type: String
    Description: Lambda unique (logical) name

  AlarmSNSTopicArn:
    Type: String
    Default: '-'
    Description: 'An ARN of an SNS topic where to send alarm when DLQ contain messages'

  FunctionBucketName:
    Type: String
    Description: S3 bucket name where the lambda code is stored

  FunctionBucketKey:
    Type: String
    Description: S3 object key where the lambda code is stored

  MemorySize:
    Type: String
    Description: memory amount reserved to the task pod.

  Timeout:
    Type: String
    Default: 10
    Description: timeout for the lambda function

  Runtime:
    Type: String
    Default: 'nodejs18.x'
  
  RoleArn:
    Type: String
    Description: Lambda role arn
  
  Handler:
    Type: String
    Description: Lambda Handler
    Default: "index.handler"
    
  # Technical parameters
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: ''
    Description: the VPC id of the vpc where's the cluster containing the current service is deployed
    
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Default: ''
    Description: the subnets where the service is going to be deployed

  # Function layers
  Layer1:
    Type: String
    Description: ARN of the first layer
    Default: ''
  
  Layer2:
    Type: String
    Description: ARN of the second layer
    Default: ''
  
  Layer3:
    Type: String
    Description: ARN of the third layer
    Default: ''
  
  Layer4:
    Type: String
    Description: ARN of the fourth layer
    Default: ''
  
  Layer5:
    Type: String
    Description: ARN of the fifth layer
    Default: ''
  
  # Tags
  Tag1Entry:
    Description: 1st tag in the form key=value
    Type: String
    Default: ''

  Tag2Entry:
    Description: 2nd tag in the form key=value
    Type: String
    Default: ''

  Tag3Entry:
    Description: 3rd tag in the form key=value
    Type: String
    Default: ''

  Tag4Entry:
    Description: 4th tag in the form key=value
    Type: String
    Default: ''
  
  Tag5Entry:
    Description: 5th tag in the form key=value
    Type: String
    Default: ''

  # Function env environment map, maximum 15 entry
  FunctionEnvEntry1:
    Description: 1st container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry2:
    Description: 2nd container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry3:
    Description: 3rd container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry4:
    Description: 4th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry5:
    Description: 5th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry6:
    Description: 6th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry7:
    Description: 7th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry8:
    Description: 8th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry9:
    Description: 9th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry10:
    Description: 10th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry11:
    Description: 11th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry12:
    Description: 12th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry13:
    Description: 13th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry14:
    Description: 14th container environment entry in the form key=value
    Type: String
    Default: ''
  FunctionEnvEntry15:
    Description: 15th container environment entry in the form key=value
    Type: String
    Default: ''
    
Conditions:
  HasVpcId: !Not [ !Equals [ !Ref VpcId, '' ] ]
  HasLayer1: !Not [ !Equals [ !Ref Layer1, '' ] ]
  HasLayer2: !Not [ !Equals [ !Ref Layer2, '' ] ]
  HasLayer3: !Not [ !Equals [ !Ref Layer3, '' ] ]
  HasLayer4: !Not [ !Equals [ !Ref Layer4, '' ] ]
  HasLayer5: !Not [ !Equals [ !Ref Layer5, '' ] ]

  # this condition will be overridden by the transform
  LamdaInsightsEnabled: !Equals [ 'true', 'false' ]

  # Tags conditions
  Tag1Exist: !Not [ !Equals [ !Ref Tag1Entry, '' ] ]
  Tag2Exist: !Not [ !Equals [ !Ref Tag2Entry, '' ] ]
  Tag3Exist: !Not [ !Equals [ !Ref Tag3Entry, '' ] ]
  Tag4Exist: !Not [ !Equals [ !Ref Tag4Entry, '' ] ]
  Tag5Exist: !Not [ !Equals [ !Ref Tag5Entry, '' ] ]

Resources:

  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: !Ref Runtime
      Role: !Ref RoleArn
      Handler: !Ref Handler
      MemorySize: !Ref MemorySize
      Timeout: !Ref Timeout
      TracingConfig:
        Mode: Active
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:339249233099:layer:LambdaInsightsExtension:13"    
        - Fn::If:
          - HasLayer1
          - !Ref Layer1
          - !Ref "AWS::NoValue"
        - Fn::If:
          - HasLayer2
          - !Ref Layer2
          - !Ref "AWS::NoValue"
        - Fn::If:
          - HasLayer3
          - !Ref Layer3
          - !Ref "AWS::NoValue"
        - Fn::If:
          - HasLayer4
          - !Ref Layer4
          - !Ref "AWS::NoValue"
        - Fn::If:
          - HasLayer5
          - !Ref Layer5
          - !Ref "AWS::NoValue" 
      Tags:
        - 'Fn::If':
          - Tag1Exist
          - Key: !Select [ 0, !Split [ "=", !Ref Tag1Entry ] ]
            Value: !Select [ 1, !Split [ "=", !Ref Tag1Entry ] ]
          - !Ref "AWS::NoValue"
        - 'Fn::If':
          - Tag2Exist
          - Key: !Select [ 0, !Split [ "=", !Ref Tag2Entry ] ]
            Value: !Select [ 1, !Split [ "=", !Ref Tag2Entry ] ]
          - !Ref "AWS::NoValue"
        - 'Fn::If':
          - Tag3Exist
          - Key: !Select [ 0, !Split [ "=", !Ref Tag3Entry ] ]
            Value: !Select [ 1, !Split [ "=", !Ref Tag3Entry ] ]
          - !Ref "AWS::NoValue"
        - 'Fn::If':
          - Tag4Exist
          - Key: !Select [ 0, !Split [ "=", !Ref Tag4Entry ] ]
            Value: !Select [ 1, !Split [ "=", !Ref Tag4Entry ] ]
          - !Ref "AWS::NoValue"
        - 'Fn::If':
          - Tag5Exist
          - Key: !Select [ 0, !Split [ "=", !Ref Tag5Entry ] ]
            Value: !Select [ 1, !Split [ "=", !Ref Tag5Entry ] ]
          - !Ref "AWS::NoValue"
      VpcConfig:
        'Fn::If':
          - HasVpcId
          - SecurityGroupIds:
              - !GetAtt FunctionSecGroup.GroupId
            SubnetIds: !Ref Subnets
          - !Ref "AWS::NoValue"
      Code:
        S3Bucket: !Ref FunctionBucketName
        S3Key: !Ref FunctionBucketKey

  FunctionSecGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: HasVpcId
    Properties:
      GroupDescription: !Sub '${FunctionName}-security-group'
      VpcId: !Ref VpcId


Outputs:
  FunctionName:
    Value: !Ref Function
  
  FunctionArn:
    Value: !GetAtt Function.Arn
